src/FormStep.js
src/formio/components/Number.js
src/formio/components/TextField.js
src/formio/validators/kvk.js
src/formio/validators/plugins.js

Fixes https://github.com/open-formulieren/open-forms/issues/463
There are two things I noticed that could be improved but I'm not sure if it's outside the scope of the ticket:
1. It would be nice to put what is in the constructors of the TextField and Number to a base component that all other components use so that any future plugins don't require configuration of our components.  There didn't seem to be a good way to do this and I'm not sure the likelihood of this happening in the future so I didn't do it now but I can if you think it's a good idea.
2. I noticed with multiple errors the text overlaps because of the `transform: translateY(-31px);`.  I don't think there is a high likelihood of having multiple validations for one component but wanted to mention it.
**Screenshot**
Error with …

Add kvk validation in frontend

---

package.json
src/FormStart.js
src/FormStep.js
src/FormStepSummary.js
src/Summary.js
src/Toolbar.js
src/i18n.js
src/scss/components/_toolbar.scss
src/sdk.js
src/utils.js
yarn.lock

- Styled login buttons to be below each other and full width on mobile
- Styled step submission buttons to be below each other and full with
- On mobile, the summary page displays the "wijzigen" link below the title rather than floating midway the page
- Swapped the (visual) order of elements on mobile so that primary buttons are on top
- Added filesize formatting for file-uploads with react-intl

Quality of life changes

---

CONTRIBUTING.md
LICENSE.md
README.NL.rst
README.rst
publiccode.yaml

Fixes https://github.com/open-formulieren/open-forms/issues/490

Open source update

---

src/DigidAuthenticationErrors.js
src/FormStart.js
src/jstests/formio/components/DigidAuthenticationErrors.spec.js
src/jstests/formio/components/FormStart.spec.js
src/jstests/formio/components/fixtures/form.js
src/scss/components/_alert.scss

Part of fixing https://github.com/open-formulieren/open-forms/issues/518

Display DigiD errors

---

src/api.js

Backend PR: https://github.com/open-formulieren/open-forms/pull/514
**Screenshot**

Session Timeout

---

src/formio/components/Select.js
src/utils.js

SDK PR for https://github.com/open-formulieren/open-forms/pull/573

Jcc afspraken

---

src/components/Card.js
src/components/ErrorBoundary.js
src/components/ErrorMessage.js
src/components/Form.js
src/components/PaymentForm.js
src/components/SubmissionConfirmation.js
src/components/Summary/index.js
src/hooks/useScrollIntoView.js
src/types/Form.js

**Changes**
* Polls status endpoint to check background processing
* Renders confirmation page content + PDF download URL on successful processing (and reference)
* Renders error message if available and processing failed
* Render payment start form to Ogone

Check the background processing status/result "while" submitting the form

---

src/formio/components/Select.js

Related backend PR here: https://github.com/open-formulieren/open-forms/pull/665
These values are changed in the backend so we need to handle these names.

Handle new naming in configuration

---

src/components/Form.js
src/components/FormStep.js
src/formio/components/Select.js
src/formio/hooks.js
src/formio/hooks/appointments.js
src/formio/plugins.js
src/sdk.js
src/utils.js

Fixes open-formulieren/open-forms#682
**Changes**
Some more details of what the flow/algorithm is...
1. A user starts filling out the form. We tap into the Formio.js change event to detect user changes and update the React state with that. The React state is then again fed to the Formio.js component, effectively replacing the Formio.js state with React state (declaratively).
2. Data changes are debounced - after 300ms we do the actual logic check with the state at that time.
- we only perform logic checks (api calls) if the data has changed from the data of the previous logic check
- we only perform logic checks if there _is_ data to check (backend otherwise returns HTTP 400)
- once a logic check is scheduled, we update what the "data of the previous logic check" was so we can make the …

Fix logic checking / infinite check loops / appointments interaction

---

src/components/FormStart/tests.spec.js
src/components/auth/AuthenticationErrors/index.js
src/components/auth/AuthenticationErrors/tests.spec.js

Part of https://github.com/open-formulieren/open-forms/issues/675

Update DigiD error message

---

package.json
scripts/i18n-formatter.js
src/components/Form.js
src/components/LogoutButton.js
src/components/PaymentForm.js
src/components/SubmissionConfirmation.js
src/components/Summary/test.spec.js
src/i18n.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/sdk.js
yarn.lock

Similar set up as the backend project, just some different folders (but same "management" commands).

Translation tooling / machinery

---

package.json
src/sdk.js
src/sentry.js
src/utils.js
yarn.lock

Fixes https://github.com/open-formulieren/open-forms/issues/657

[#657] Set up SDK Sentry

---

package.json
src/components/Price.js
src/components/Summary/index.js
src/components/Summary/test.spec.js
src/hooks/useRefreshSubmission.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/scss/components/_price.scss
src/styles.scss

Part of https://github.com/open-formulieren/open-forms/issues/264

Add price to summary page

---

src/components/FormStep.js

Fixes https://github.com/open-formulieren/open-forms/issues/716

Hide save step button

---

src/components/Form.js
src/components/Summary/index.js
src/formio/hooks/appointments.js

Fixes open-formulieren/open-forms#725
Note: 
The issue said: _The error is not cleared when the user changes (the relevant) data_
For simplicity I went for clearing the error when the user navigates back to the form steps.

[open-formulieren/open-forms#725] Apointment improvements

---

src/formio/components/Select.js
src/scss/components/_select.scss

Improvements to the ChoiceJS widget style: https://watch.screencastify.com/v/y1LtmelivPdspMkaeTUL
Backend PR to make select widget configurable: https://github.com/open-formulieren/open-forms/pull/883

Select style

---

src/formio/templates/library.js
src/formio/templates/multiValueRow.js
src/formio/templates/multiValueTable.js
src/scss/components/_multi-value-row.scss
src/scss/components/_multi-value-table.scss
src/styles.scss

[#8] Style multiple-value input

---

src/formio/components/Password.js
src/formio/module.js
src/utils.js

SDK PR for https://github.com/open-formulieren/open-forms/pull/906

Add password component

---

src/components/Button.js
src/components/FormStart/index.js
src/components/FormStep.js
src/components/Loader.js
src/scss/components/_button.scss
src/scss/components/_loading.scss

Fixes open-formulieren/open-forms#874

Tweak disabled button for accessibility

---

package.json
src/formio/components/TimeField.js
src/formio/validators/MinMaxTimeValidator.js
src/jstests/formio/components/fixtures/time.js
src/jstests/formio/components/ibanfield.spec.js
src/jstests/formio/components/time.spec.js

Part of https://github.com/open-formulieren/open-forms/issues/902

Validate time on min/max value

---

src/components/FormStepSummary/index.js
src/utils.js

Related to https://github.com/open-formulieren/open-forms/issues/974
- Fix array values in summary page

Improvements sprint 9 demo

---

src/components/FormStep.js

Setting the submission data as prop was used to process backend data
loading events declaratively (navigating between steps, logic
evaluation...). However, because the prop changed, this caused FormIO
to re-render too aggressively, breaking the cursor position and leading
to a frustrating experience while filling out non-standard fields (
such as time field, currency field...).
This has been removed, and we now sync the FormIO state on backend
data updates (initial step data loading, logic updates...). This
makes the form less jittery and more user-friendly.
Fixes open-formulieren/open-forms#876
Fixes open-formulieren/open-forms#878
Breaks ??? (<- we will find out...)

Remove submission data prop and instead use event handler

---

src/components/SubmissionConfirmation.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Fixes https://github.com/open-formulieren/open-forms/issues/980

Added generic error message on Submission failure

---

src/components/Price.js
src/components/Summary/index.js
src/types/Submission.js

Fixes open-formulieren/open-forms#235

API can return null for payment amount

---

src/formio/components/LicensePlateField.js
src/formio/module.js
src/jstests/formio/components/fixtures/licenseplate.js
src/jstests/formio/components/licenseplate.spec.js

Fixes https://github.com/open-formulieren/open-forms/issues/195

License plate field

---

src/components/FormStart/index.js
src/types/Form.js

Fixes https://github.com/open-formulieren/open-forms/issues/830

Explanation text on start page

---

src/Context.js
src/components/Button.js
src/components/CoSign.js
src/components/FormStart/index.js
src/components/FormStep.js
src/components/FormStepSummary/index.js
src/components/FormStepSummary/utils.js
src/components/LoginButton/LoginButtonIcon.js
src/components/LoginButton/index.js
src/components/Summary/index.js
src/components/Toolbar.js
src/formio/components/CoSign.js
src/formio/module.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/scss/components/_co-sign.scss
src/styles.scss

Fixes open-formulieren/open-forms#296

Co-sign Formio/React component

---

src/components/FormStepSummary/fixtures.js
src/components/FormStepSummary/test.spec.js
src/components/FormStepSummary/utils.js

Part of https://github.com/open-formulieren/open-forms/issues/1064

Multivalue select field in summary

---

src/i18n/compiled/nl.json
src/i18n/messages/nl.json

Some left over untranslated strings.

Updated translations

---

src/components/Summary/index.js

Forgotten reference to canSubmit field

---

src/components/Summary/index.js

Part of open-formulieren/open-forms#1072

Price not displayed if user has paid

---

src/components/ProgressIndicator/CompletionMark.js
src/components/ProgressIndicator/ProgressItem.js
src/components/ProgressIndicator/index.js
src/formio/templates/columns.js
src/formio/templates/library.js
src/scss/components/_columns.scss
src/scss/components/_fieldset.scss
src/scss/components/_form-control.scss
src/scss/components/_progress-indicator.scss

Fixes https://github.com/open-formulieren/open-forms/issues/929

UI improvements

---

src/components/Map/index.js

Fixes open-formulieren/open-forms#864

Fix map component if the user rejects location sharing in the browser

---

package.json
src/api.js
src/components/Form.js
src/components/FormStepDebug.js
src/components/Sessions/RequireSession.js
src/components/Sessions/SessionExpiry.js
src/components/Sessions/index.js
src/hooks/useSessionTimeout.js
yarn.lock

Fixes open-formulieren/open-forms#1155
---
Depends on https://github.com/open-formulieren/open-forms/pull/1156
---
Minimal effort to handle expired sessions towards the end-user. We set up a timer to mark the session as expired, and render an error message if that expiry indeed occurs.
Contains some preliminary work to display the time left to the end-user, disabled at the moment because I'm not sure where put/how to style it.
This also provides a basis for a future warning/popup/modal if the session is close to expiring to give the user a chance of extending it.

Detect session expiration

---

src/components/FormStep.js

Related to open-formulieren/open-forms#994
This `filterOutBlankValues` was probably a left-over from when we would pass the submission (data) as a prop to the underlying FormIO React component, which would then behave weirdly with blank values on required fields.
Since we've switched to using a `ref` to avoid having to rebuild the Formio component tree all the time (when data changes, when configuration changes because of logic...), this appears to not be needed anymore.
If we _do_ keep this, then form fields configured with a default value that are optional actually are bugged, as the explicit empty/blank values are filtered out and then Formio sets up the default value again instead.

Do not filter out blank values in logic check or submission loading

---

src/formio/components/BsnField.js

Fixes https://github.com/open-formulieren/open-forms/issues/1162

[#1162] Fixed BSN field validator validating everything not 9 chars long

---

src/components/FormStep.js

Part of https://github.com/open-formulieren/open-forms/issues/877

[#887] Fixed immutable state data leaking into formio and erroring when mutated

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/components/FormStepSummary/index.js
src/components/FormStepSummary/test.spec.js
src/components/FormStepSummary/utils.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Related to https://github.com/open-formulieren/open-forms/issues/1166#issuecomment-1013017659

Fix summary value display

---

.bumpversion.cfg
.github/workflows/ci.yml
CHANGELOG.rst
README.NL.rst
README.rst
config/paths.js
package.json
publiccode.yaml

* Sets up bumpversion
* Created initial changelog
Example usage after deploy: configure Open Forms (backend) to use:
```
SDK_BASE_URL=http://localhost:8080/1.0.0-rc.0
```

Prepare 1.0.0-rc.0 version

---

Dockerfile
nginx.conf

Rootless is more better.
NOTE: this requires updating the frontend!

Base nginx container on nginx-unprivileged

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/components/FormStepSummary/fixtures.js
src/components/FormStepSummary/test.spec.js

Fixes open-formulieren/open-forms#1203

[OF#1203] Fix summary page with empty file upload

---

src/formio/validators/MinMaxTimeValidator.js
src/jstests/formio/components/time.spec.js

Fixes https://github.com/open-formulieren/open-forms/issues/1152

[OF#1152] Time validation

---

src/i18n/compiled/nl.json
src/i18n/messages/nl.json

Fixes open-formulieren/open-forms#1240

Update resume form message

---

src/formio/components/Currency.js
src/jstests/formio/components/currency.spec.js
src/jstests/formio/components/fixtures/currency.js

Fixes https://github.com/open-formulieren/open-forms/issues/1270

[OF#1270] Formatting currency with no decimals

---

src/formio/components/TextField.js
src/jstests/formio/components/fixtures/textfield.js
src/jstests/formio/components/textfield.spec.js

Fixes https://github.com/open-formulieren/open-forms/issues/1284

[OF#1284] Refresh prefill address on invalid data

---

src/scss/components/_file-upload.scss

Fixes open-formulieren/open-forms#1262

[OF#1262] Fix file upload style file if filename is too long

---

src/components/PrivacyCheckbox.js
src/scss/components/_privacy-checkbox.scss

Fixes open-formulieren/open-forms#1261

[OF#1261] Fix privacy-checkbox styling

---

src/components/FormStep.js

Fixes open-formulieren/open-forms#1274
As suspected already, the formData ref can be refactored out, since the
formRef (if set) contains the same information (the submission data).
The updating of the formData ref lagged behind one tick to what the
actual submission data value was. This _can_ cause race conditions in
the logic check handling where values are set based on formData ref.
The surface for race conditions is now further reduced by relying on
the Formio instance in all cases.
I could reproduce this by putting some `await sleep(5000)` between lines of code that are not IO bound. Hopefully this fixes it, as this is otherwise rather hard to reproduce.

Fixes more event/race conditions while typing

---

src/components/FormStep.js

Fixes open-formulieren/open-forms#942
Backend calls to submit the data take up a non-finite amount of time,
so now we mark navigation access so that a loader is rendered while
the backend is processing.

Improve user experience when navigating between steps

---

src/components/FormStart/index.js
src/components/SubmissionConfirmation.js
src/scss/_settings.scss
src/scss/components/_content.scss
src/scss/components/_file-upload.scss
src/scss/components/_multi-value-row.scss
src/scss/components/_privacy-checkbox.scss
src/scss/components/_signature.scss
src/scss/components/_typography.scss

Fixes open-formulieren/open-forms#1018

[open-formulieren/open-forms#1018] WCAG accessibility fixes

---

src/scss/components/_form-control.scss

Fixes https://github.com/open-formulieren/open-forms/issues/1340

[OF#1340] Update asterix style

---

src/formio/components/BsnField.js
src/formio/components/DateField.js
src/formio/components/PhoneNumberField.js

Related to https://github.com/open-formulieren/open-forms/issues/1301

Fixed some SDK bugs

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/components/FormStepSummary/test.spec.js

Relates to open-formulieren/open-forms#1301

Fixes to ComponentValueDisplay.js

---

src/formio/hooks/appointments.js

Fixes open-formulieren/open-forms#1374

Fix broken appointments flow

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Release candidate 3

---

src/components/Summary/index.js
src/scss/components/_input.scss

Part of  https://github.com/open-formulieren/open-forms/issues/1393

Readonly fields

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml
src/i18n/compiled/nl.json
src/i18n/messages/nl.json

Release checklist:
**Release blockers**
- #176

Bump to version 1.0.0 and update changelog

---

src/components/FormStep.js
src/formio/templates/component.ejs
src/formio/templates/label.ejs
src/scss/components/_form-control.scss
src/types/Form.js

Part of https://github.com/open-formulieren/open-forms/issues/1404

[OF#1404] Required fields without asterisks

---

src/components/ButtonsToolbar/index.js
src/components/ButtonsToolbar/test.spec.js
src/components/FormStep.js
src/components/Summary/index.js
src/components/Summary/test.spec.js

Backend part: https://github.com/open-formulieren/open-forms/pull/1419

[#1418] Implemented Submission.isAuthenticated for LogoutButton visibility

---

src/components/FormStep.js

Fixes open-formulieren/open-forms#1076
The problem seems to be that whenever there is a TextField with validation plugin (like checking that the KVK is valid) in a form step, submitting the form step with empty required fields doesn't raise an error.
Problem with required fields and errors not blocking validation:
https://github.com/open-formulieren/open-forms-sdk/blob/main/src/formio/components/TextField.js#L29
If this function is commented out, the required fields block step submission. 
This function specifies that validation is meant to happen async. (setting async: false makes the required validator block the submission, but the promise of the async KVK validation never gets settled).

[OF#1076] Catch Formio invalid data check

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml

SDK release to be bundled in Open Forms 1.0.3

1.0.1 bugfix release

---

src/formio/components/FileField.js
src/formio/templates/file.ejs
src/jstests/formio/components/file.spec.js

Fixes https://github.com/open-formulieren/open-forms/issues/1449
Backend PR: https://github.com/open-formulieren/open-forms/pull/1450
Note: I couldn't figure out how to write tests for the behaviour of the custom template

[OF#1449] Custom setting for max number of files

---

src/components/Form.js
src/components/FormStart/index.js
src/components/LoginButton/index.js
src/components/constants.js
src/components/utils.js
src/hooks/useAutomaticRedirect.js
src/hooks/useStartSubmission.js
src/sdk.js
src/types/Form.js

Fixes https://github.com/open-formulieren/open-forms/issues/1313
related PR in backend: https://github.com/open-formulieren/open-forms/pull/1429

:sparkles: Add option to auto redirect user to login

---

src/components/Form.js

Backend: https://github.com/open-formulieren/open-forms/pull/1446

[#1441] Changed logout URL to submission specific

---

src/components/Summary/index.js

Fixes https://github.com/open-formulieren/open-forms/issues/1479

[OF#1479] Hide not applicable steps in summary page

---

src/components/FormStepSummary/fixtures.js
src/components/FormStepSummary/index.js
src/components/FormStepSummary/test.spec.js
src/components/FormStepSummary/utils.js

Part of open-formulieren/open-forms#1527

[OF#1527] Hidden fields in summary

---

src/components/FormStep.js

Fixes open-formulieren/open-forms#1494
Given that:
1. a form was in a submittable state
2. user input in the form step is done in quick succession but the net
end result is no changes (e.g. radio yes/no toggle to the other
option and quickly back to the originally selected option)
Then the change handler caused the form submission to be blocked as
a safeguard against bypassing logic checks.
The logic check in turn shortcutted because the data being compared
was not different than the originally checked data, so no changes in
state are suspected.
However, this shortcut/guard clause failed to restore the original
canSubmit state of the form step, which was set to false by the
change handler.
This patch ensures that on early-exits of logic checks, the state is
correctly restored. …

Fix broken logic state for formstep submission

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml

Release 1.0.2

---

src/formio/templates/file.ejs

Fixes open-formulieren/open-forms#1538

[#1538] Fixed regression in file-component template controls when multiple=true

---

package.json
src/formio/components/Content.js
src/scss/components/_form-control.scss
yarn.lock

Part of https://github.com/open-formulieren/open-forms/issues/1541

[OF#1541] CSS classes component

---

src/formio/components/FileField.js
src/formio/templates/file.ejs

Fixes https://github.com/open-formulieren/open-forms/issues/1555
Translations: https://github.com/open-formulieren/open-forms/pull/1557
While uploading:

File upload component improvements

---

src/components/Button.js
src/components/FormStepSummary/fixtures.js
src/components/PrivacyCheckbox.js
src/components/SummaryConfirmation/index.js
src/scss/components/_privacy-checkbox.scss

Fixes https://github.com/open-formulieren/open-forms/issues/1580

[OF#1580] Warning to accept privacy policy

---

src/formio/components/FileField.js

Fixes open-formulieren/open-forms#1539
Sigh... Formio pls.
So much global stuff leaks into component behaviour that isn't even
necessary.

Fix DELETE call not being made for removed file uploads

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml

Bump version to 1.0.3 and update changelog

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
bin/find_untranslated_js.py
package.json
publiccode.yaml
src/i18n/compiled/nl.json
src/i18n/messages/nl.json

1.1.0 release candidate

---

src/components/FormStep.js

Fixes open-formulieren/open-forms#1526
On input data change, the backend logic evaluation is now always
performed (i.e. even if the client-side validation reports an
invalid form). However, only the data that validated is sent to the
backend.
This fixes situations where the backend form logic is required to
resolve the client-side validation errors, typically when a former
form field is returned to which triggers some logic.

Always call backend logic, but only with valid data

---

src/hooks/usePageViews.js

Related to open-formulieren/open-forms#1716

Update documentation for piwik pro

---

.gitignore
src/formio/components/TextField.js
src/jstests/formio/components/textfield.spec.js

Fixes open-formulieren/open-forms#1717

Handle unusable autofilled field — [open-formulieren/open-forms#1717]

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/components/FormStepSummary/SummaryEditGrid.js
src/components/FormStepSummary/index.js
src/components/FormStepSummary/utils.js
src/formio/components/EditGrid.js
src/formio/components/Number.js
src/formio/components/PhoneNumberField.js
src/formio/components/TextField.js
src/formio/module.js
src/formio/templates/editGrid.ejs
src/formio/templates/editGridRow.ejs
src/formio/templates/library.js
src/formio/validators/plugins.js
src/scss/components/_editgrid.scss
src/scss/components/_summary-row.scss
src/styles.scss

Part of https://github.com/open-formulieren/open-forms/issues/1710
The summary page now looks like this:
After writing the renderer in the backend, im in doubt if I should have gone for the same approach (i.e. the fields being displayed under rather than next to the label) :thinking:

[OF#1710] Repeating groups

---

src/components/FormStep.js

Fixes open-formulieren/open-forms#1868

Re-add non validated data to step data

---

src/api.js
src/index.js

Part of https://github.com/open-formulieren/open-forms/issues/1944

[OF#1944] Handle CSRF token

---

src/scss/components/_content.scss

Part of open-formulieren/open-forms#1964
Before:
After:

[OF#1964] Adjust padding on content components with CSS class

---

src/components/FormStart/index.js

Fixes open-formulieren/open-forms#1933

Remove hardcoded explanation message [open-formulieren/open-forms#1933]

---

src/api.js
src/components/Button.js
src/components/ErrorBoundary.js
src/components/Form.js
src/components/FormStart/index.js
src/components/FormStep.js
src/components/MaintenanceMode.js
src/components/RequireSubmission.js
src/errors.js
src/hooks/useRecycleSubmission.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/utils.js

Fixes open-formulieren/open-forms#1967
* Form designers get a warning but can continue (maintenance mode)
* Everyone gets an error message for deactivated forms

Handle maintenance mode forms & deactivated forms

---

src/components/FormStep.js
src/components/ProgressIndicator/index.js
src/components/ProgressIndicator/test.spec.js

Fixes https://github.com/open-formulieren/open-forms/issues/1944

Navigate between steps

---

src/components/FormStepSummary/fixtures.js
src/components/FormStepSummary/index.js
src/types/Submission.js

We did not use them, except for specifying them in the proptypes.

2.0 backend removed some deprecated attributes

---

src/formio/components/EditGrid.js

Fixes open-formulieren/open-forms#2075
Problematic code in Formio: https://github.com/formio/formio.js/blob/4.12.7.x/src/components/editgrid/EditGrid.js#L892

Wrap errors in translate function

---

src/components/ButtonsToolbar/index.js

Fixes open-formulieren/open-forms#2077
The checkbox seems to have been fixed by the restyling (https://github.com/open-formulieren/open-forms-sdk/pull/236)

[OF#2077] Make 'previous page' accessible with tab-navigate

---

src/components/FormStep.js

Fixes open-formulieren/open-forms#2082

[OF#2082] Jump to component with error when submitting step

---

src/formio/templates/editGrid.ejs
src/scss/components/_editgrid.scss
src/scss/components/_form-control.scss

Fixes open-formulieren/open-forms#2073
Fixes open-formulieren/open-forms#2067

Remove accidental styling of content components

---

src/components/FormStep.js

Fixes open-formulieren/open-forms#2035

[OF#2035] Scroll to top on step load

---

package.json
src/formio/components/EditGrid.js
src/formio/components/Email.js
src/formio/components/FileField.js
yarn.lock

Fixes open-formulieren/open-forms#551

Upgrade Formiojs

---

src/formio/components/FileField.js
src/formio/module.js
src/formio/plugins.js

* File upload was affected
* File delete was affected
* Validation was not affected
* Cancel appointment was not affected

Ensure that CSRF token is sent along for unsafe endpoints

---

src/formio/components/Columns.stories.mdx
src/formio/components/story-util.js
src/formio/templates/columns.ejs
src/scss/components/_columns.scss

Easiest to check by running storybook locally with `yarn storybook` :)

Columns styling + mobile look/customization

---

package.json
src/scss/components/_file-upload.scss

Fixes open-formulieren/open-forms#2137
Design-token: https://github.com/open-formulieren/design-tokens/pull/3

[OF#2137] Use design token for file upload padding

---

src/scss/components/_progress-indicator.scss

Fixes open-formulieren/open-forms#2138
Design Token: https://github.com/open-formulieren/design-tokens/pull/4

[OF#2138] Design token margin progress indicator mobile

---

package.json
src/scss/components/_fieldset.scss

Fixes open-formulieren/open-forms#2142
Design token: https://github.com/open-formulieren/design-tokens/pull/5

[OF#2142] Design token fieldset legend

---

src/scss/components/_content.scss

Fixes open-formulieren/open-forms#2149

[OF#2149] Remove padding if content is first child

---

src/components/FormStepSummary/index.js
src/components/FormStepSummary/test.spec.js
src/scss/_settings.scss
src/scss/components/_summary-row.scss
src/scss/components/_summary.scss
src/scss/components/_toolbar.scss
src/styles.scss

Fixes https://github.com/open-formulieren/open-forms/issues/2129
Design token for spacing between rows https://github.com/open-formulieren/design-tokens/pull/2
Desktop:
Mobile:
Mobile header if the step name is too long to fit on one line:

[OF#2129] Summary page style

---

package.json
src/scss/components/_input.scss
src/scss/components/_label.scss

Fixes open-formulieren/open-forms#2150
Design token https://github.com/open-formulieren/open-forms-sdk/pull/262

[OF#2150] Label bold, input not

---

src/scss/_settings.scss

Fixes open-formulieren/open-forms#2152
Design token: https://github.com/open-formulieren/design-tokens/pull/7

[OF#2152] Design token for font

---

src/formio/components/Checkbox.stories.mdx

Fixes open-formulieren/open-forms#1345

[OF#1345] Add story for required checkbox

---

src/formio/components/Currency.js
src/formio/components/Number.js

Part of open-formulieren/open-forms#1351

[OF#1351] Allow negative numbers

---

src/hooks/usePageViews.js

Fixes open-formulieren/open-forms#1180

[OF#1180] Fix gtag calls

---

src/types/Form.js

Issue: #2232
Related to https://github.com/open-formulieren/open-forms/pull/2261

:sparkles: [#2232] Add i18nEnabled to Form PropTypes

---

src/formio/components/FileField.js

Fixes open-formulieren/open-forms#2335

[OF#2335] Re-display drag&drop on cancel upload

---

src/components/App.js
src/sdk.spec.js

Closes open-formulieren/open-forms#2254
Based on #273

Conditionally render language selection component

---

src/formio/templates/editGrid.ejs
src/scss/components/_editgrid.scss
src/scss/components/_form-control.scss

Part of open-formulieren/open-forms#2344

[OF#2344] Put asterisk next to repeating group label

---

.storybook/preview.js
src/components/App.stories.mdx

Complements #277, but the Storybook Docs don't render :frowning_face:  Feel free to look into this, I'm moving on.
Tests (and should document) open-formulieren/open-forms#2254

Stories for conditionally rendering LanguageSelector

---

src/components/App.js
src/components/AppDebug.js
src/components/FormStepDebug.js
src/scss/components/_debug-info.scss
src/styles.scss

:hammer: Break out global app debug info into component

---

src/components/ProgressIndicator/ProgressIndicatorDisplay.js
src/components/ProgressIndicator/constants.js
src/components/ProgressIndicator/index.js
src/components/ProgressIndicator/index.stories.mdx
src/components/ProgressIndicator/test.spec.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Fixes open-formulieren/open-forms#2374

[OF#2374] Split progress indicator

---

src/components/FormStepSummary/index.js

fixes https://github.com/open-formulieren/open-forms/issues/2267

Set semantic headings

---

src/components/FormStep.js

Fixes open-formulieren/open-forms#2407

[OF#2407] Scroll only on submit

---

src/formio/components/Checkbox.stories.mdx
src/formio/components/story-util.js
src/formio/templates/checkbox.ejs

Fixes open-formulieren/open-forms#2406

[OF#2406] Make required checkboxes consistent in style

---

src/components/FormStep.js

Fixes open-formulieren/open-forms#2431

[OF#2431] Just jump the focus after submission to the top component with errors

---

src/formio/components/Selectbox.stories.mdx

Fixes open-formulieren/open-forms-sdk#305

:memo: [#305] add Storybook Selectboxes component

---

src/formio/components/Signature.stories.mdx

fixes open-formulieren/open-forms-sdk#304

:memo: [#304] add Storybook Signature component

---

src/formio/components/Content.stories.mdx

Fixes open-formulieren/open-forms-sdk#306

:memo: [#306] add Storybook Content component

---

src/components/FormStep.js
src/formio/components/EditGrid.js

Fixes open-formulieren/open-forms#2488

[OF#2488] Force logic re-evaluation on row delete

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Release 1.3.0 alpha.1

---

src/components/ProgressIndicator/ProgressIndicatorDisplay.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Extra fixes for https://github.com/open-formulieren/open-forms/issues/2267

:wheelchair: nr.2267 Progress indicator semantics

---

src/components/Body.js
src/components/Body.stories.mdx
src/components/ProgressIndicator/ProgressIndicatorDisplay.js

Fixes open-formulieren/open-forms#2502
- font-size of progress indicator components is increased by adding a modifier

[#2502] fix styling of progress indicator

---

src/formio/components/Fieldset.stories.mdx

Fixes open-formulieren/open-forms-sdk#307

:memo: [#307] add Storybook Fieldset component

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/formio/components/DateTimeField.js
src/formio/components/DateTimeField.stories.mdx
src/formio/module.js

Part of open-formulieren/open-forms#2557

[OF#2557] Add datetime component

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml

Prepare 1.3.0-beta.0 release

---

src/formio/templates/file.ejs

Closes open-formulieren/security-issues#22
Problem is also reported to Formio.

Fix self-XSS in file names uploaded files

---

src/scss/components/_progress-indicator.scss

Fix styling bugs

---

src/components/Summary/index.js

Part of https://github.com/open-formulieren/open-forms/issues/2646

[OF#2646] Persist privacy policy

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/components/FormStepSummary/test.spec.js

Fixes open-formulieren/open-forms#2708

[OF#2708] Render zeroes

---

package.json
src/components/ProgressIndicator/ProgressIndicatorDisplay.js
src/scss/components/_progress-indicator.scss

Closes open-formulieren/open-forms#2675

[#2675] make progress indicator sticky]

---

src/formio/components/EditGrid.stories.mdx
src/formio/components/story-util.js

:memo: [#311] add Storybook Edit Grid / Repeating Group

---

.bumpversion.cfg
README.NL.rst
README.rst
package.json
publiccode.yaml

Changelogs are deliberately not being updated just yet.

Release 1.2.6

---

.storybook/main.js
.storybook/preview.js
package.json
public/mockServiceWorker.js
src/components/App.stories.mdx
src/components/LanguageSelection/LanguageSelection.stories.mdx
src/components/LanguageSelection/mocks.js
src/i18n.stories.mdx
yarn.lock

Closes #365
Phase one - this replaces the storybook addon. In a separate PR, the unit test mocks will be refactored.

Replace mock addon with msw

---

src/formio/templates/editGrid.ejs

[#337] add translation for groupLabel via ctx.t(...)

---

.git-blame-ignore-revs
.prettierrc.json
src/components/App.stories.mdx
src/components/FormStep.stories.mdx
src/components/FormStep/FormStep.stories.mdx
src/components/FormStep/index.js
src/components/FormStep/mocks.js
src/components/LanguageSelection/LanguageSelection.stories.mdx
src/components/LanguageSelection/mocks.js
src/components/ProgressIndicator/index.stories.mdx
src/i18n.stories.mdx
src/story-utils/decorators.js
src/story-utils/mocks.js
src/types/Form.js

Closes #366
* Added mocks for form detail, submission detail, submission step detail and submission step logic check endpoints
* Added FormStep.js component to storybook

Document FormStep component in Storybook

---

src/components/ProgressIndicator/index.js
src/components/ProgressIndicator/test.spec.js

Fixes open-formulieren/open-forms#2096

[OF#2096] Make overview not clickable if a step is blocked

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml
src/i18n/compiled/nl.json
src/i18n/messages/nl.json

Prepare 1.3.0 release

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/components/FormStepSummary/test.spec.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Fixes open-formulieren/open-forms#2760

[OF#2760] Checkbox capitalised

---

src/api-mocks/forms.js
src/components/FormStep/index.js
src/components/modals/FormStepSaveModal.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/types/Form.js

Fixes open-formulieren/open-forms#2789
Backend PR: https://github.com/open-formulieren/open-forms/pull/2876

[OF#2789] Improve pause modal text

---

src/formio/components/FileField.stories.mdx
src/formio/components/FileUpload.mocks.js

:memo: [#308] add Storybook File-Upload component

---

src/components/ButtonsToolbar/index.js

https://github.com/open-formulieren/open-forms-sdk/commit/cfcb67e33be56a753d9100c141fd83b5a2afadc8 
Part of open-formulieren/open-forms#2888

[OF#2077 + OF#2888] Keyboard navigation to previous page

---

src/scss/components/_react-modal.scss
src/scss/components/_typography.scss

Fixes open-formulieren/open-forms#2907

[OF#2907] Avoid clipping title with ellipsis

---

src/formio/components/Currency.js
src/formio/components/Number.js
src/jstests/formio/components/currency.spec.js
src/jstests/formio/components/fixtures/number.js
src/jstests/formio/components/number.spec.js

Fixes open-formulieren/open-forms#2903

[OF#2903] Fix emptying values for currencies and numbers

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml

Preparing release 1.3.1
=> translations don't seem to need changes

🔖 Release 1.3.1

---

src/components/Card.js
src/components/FormStep/index.js
src/components/ProgressIndicator/ProgressIndicatorDisplay.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/scss/components/_card.scss
src/scss/components/_progress-indicator.scss

Fixes open-formulieren/open-forms#2921

[OF#2921] Add form title to form step

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml

Release 1.3.2

---

CHANGELOG.rst

This adds the changelog entries for the past patch releases

Add missing changelog entries

---

src/api-mocks/forms.js
src/components/ButtonsToolbar/index.js
src/components/ButtonsToolbar/test.spec.js
src/components/FormStep/FormStep.stories.mdx
src/components/FormStep/index.js

Depends on: https://github.com/open-formulieren/open-forms/pull/3006

:sparkles: - Hide suspend button if suspending form is not allowed.

---

src/components/ExistingSubmissionOptions.js
src/components/Form.js
src/components/FormStart/index.js
src/components/FormStart/tests.spec.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/scss/components/_toolbar.scss

Fixes open-formulieren/open-forms#2986

[OF#2986] Make existing submission obvious

---

src/components/Form.js
src/components/FormStep/index.js
src/components/modals/FormStepSaveModal.js
src/components/modals/FormStepSaveModal.stories.mdx

Fixes open-formulieren/open-forms#2929

[OF#2929] Restarting form after pause

---

src/components/Form.js
src/components/FormStep.js
src/components/modals/FormStepSaveModal.js

Fixes https://github.com/open-formulieren/open-forms/issues/2929 (in 1.2.x)

Backport of OF#2929 to 1.2.x

---

src/components/Form.js
src/components/FormStep/index.js
src/components/modals/FormStepSaveModal.js
src/components/modals/FormStepSaveModal.stories.mdx

Fixes open-formulieren/open-forms#2929 (in 1.3.x)

Backport of OF#2929 to 1.3.x

---

src/formio/components/FileField.js
src/formio/components/FileField.stories.mdx

Fixes open-formulieren/open-forms#3040

[OF#3040] Improve error messages for file components

---

package.json
src/components/Card.js
src/components/FormStep/index.js
src/scss/components/_card.scss
yarn.lock

Leftover from open-formulieren/open-forms#2921
I didnt like how close the header was to the label of the first field:

Added padding under form step header

---

src/components/forms/EmailField/EmailField.js
src/components/forms/EmailField/EmailField.stories.mdx

Closes open-formulieren/open-forms#3059

:sparkles: [open-formulieren/open-forms#3059] Implemented Email Field, Story, and Test.

---

src/formio/components/CoSignOld.js
src/formio/components/Cosign.js
src/formio/module.js

part of open-formulieren/open-forms#1530

[OF#1530] Part 2 - add cosign component

---

src/components/forms/NumberField/NumberField.js
src/components/forms/NumberField/NumberField.stories.mdx

I went ahead and explored some ideas - I'm relatively satisfied with these though I still have some concerns. See the comments/annotations on the PR itself.

Number field improvements

---

package.json
src/components/forms/NumberField/NumberField.js
src/components/forms/NumberField/NumberField.stories.mdx
yarn.lock

Closes open-formulieren/open-forms#3058

:sparkles: Features #3058 Implemented Number Field, Story, and Test.

---

package.json
src/components/forms/SelectField/AsyncSelectField.js
src/components/forms/SelectField/SelectField.js
src/components/forms/SelectField/SelectField.stories.mdx
src/components/forms/SelectField/index.js
src/components/forms/index.js
src/scss/components/_rs-select.scss
src/styles.scss
yarn.lock

Closes open-formulieren/open-forms#3061

[open-formulieren/open-forms#3061] Feature: Select Field

---

package.json
yarn.lock

In other PRs I bumped the Utrecht tokens, might as well do Den Haag and see which theme improvements we get along with it.

Bump den haag design tokens package

---

src/formio/components/EditGrid.js
src/jstests/formio/components/editgrid.spec.js
src/jstests/formio/components/fixtures/editgrid.js

Backport of https://github.com/open-formulieren/open-forms-sdk/pull/439

[OF#3096] Backport to 1.2.x

---

src/formio/components/EditGrid.js
src/jstests/formio/components/editgrid.spec.js
src/jstests/formio/components/fixtures/editgrid.js

Backport of https://github.com/open-formulieren/open-forms-sdk/pull/439

[OF#3096] Backport to 1.3.x

---

.storybook/main.js
package.json
src/components/App.stories.mdx
src/components/FormStep/FormStep.stories.mdx
src/components/ProgressIndicator/index.stories.mdx
src/components/Summary/Summary.stories.mdx
src/components/Toolbar.js
src/components/modals/FormStepSaveModal.stories.mdx
src/sdk.js
src/story-utils/decorators.js
yarn.lock

Required for #438 
Testing the main form UX by navigating through steps. It seems to work, but there are some React warnings to investigate at some point.

Prepare for datarouter

---

package.json
src/components/appointments/ChooseProductStep.js
src/components/appointments/ChooseProductStep.stories.mdx
src/components/appointments/DateSelect.stories.mdx
src/components/appointments/LocationAndTimeStep.js
src/components/appointments/LocationAndTimeStep.spec.js
src/components/appointments/LocationAndTimeStep.stories.mdx
src/components/appointments/LocationSelect.stories.mdx
src/components/appointments/ProductSelect.stories.mdx
src/components/appointments/TimeSelect.stories.mdx
src/components/forms/DateField/DateField.js
src/components/forms/NumberField/NumberField.js
src/components/forms/SelectField/SelectField.js
src/scss/components/_floating-widget.scss

Closes open-formulieren/open-forms#3065
~~Depends on #452~~

Location and time step for appointments

---

src/sdk.js

We discussed that we will set up some tests that would have caught this

:pencil2: Typo in basePath

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
docker/ci/config.json
package.json
publiccode.yaml

Prepare 1.4.0 release

---

src/formio/templates/checkbox.ejs
src/formio/templates/label.ejs

Partly closes open-formulieren/open-forms#1892

Add tooltips

---

src/components/appointments/ChooseProductStep.stories.js
src/components/appointments/ContactDetailsStep.js
src/components/appointments/ContactDetailsStep.mdx
src/components/appointments/ContactDetailsStep.stories.js
src/components/appointments/CreateAppointment.js
src/components/appointments/CreateAppointment.stories.js
src/components/appointments/LocationAndTimeStep.js
src/components/appointments/LocationAndTimeStep.stories.js
src/components/appointments/mocks.js
src/components/formio/FormioComponent.js
src/components/formio/date.js
src/components/formio/email.js
src/components/formio/index.js
src/components/formio/radio.js
src/components/formio/textfield.js
src/components/forms/DateField/DateField.js
src/components/forms/DateField/DateInputGroup.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Closes open-formulieren/open-forms#3066
Depends on #475
TODO

Customer contact details step

---

src/components/appointments/CreateAppointment.js

Store appointment data in session storage

---

src/api-mocks/forms.js
src/components/App.js
src/components/appointments/ChooseProductStep.js
src/components/appointments/ChooseProductStep.stories.js
src/components/appointments/Context.js
src/components/appointments/CreateAppointment.js
src/components/appointments/CreateAppointment.mdx
src/components/appointments/CreateAppointment.stories.js
src/types/Form.js

Blocked by https://github.com/open-formulieren/open-forms/pull/3210
It's possible an appointment backend does not support multiple products flows, so in that situation the frontend must limit itself to a single product.

Handle updated appointment metadata in form

---

.prettierrc.json
src/components/Form.js
src/components/LanguageSelection/LanguageSelection.js
src/components/Loader.js
src/components/Loader.stories.js
src/components/Sessions/RequireSession.js
src/components/appointments/CreateAppointment.js
src/data/submissions.js
src/hooks/useGetOrCreateSubmission.js

Wrap the appointment form in session guard.
Since a submission must be present in the session, we have to anticipate timed-out sessions in the frontend.

Wrap appointment in RequireSession

---

.storybook/decorators.js
src/components/Summary/test.spec.js
src/components/forms/DateField/DateField-inputgroup.stories.js
src/components/forms/DateField/DateField.js
src/components/forms/DateField/DateInputGroup.js
src/components/forms/DateField/DatePicker.js
src/components/forms/DateField/DatePickerCalendar.js
src/components/forms/DateField/utils.js
src/components/forms/DateField/utils.spec.js
src/components/forms/EmailField/EmailField.stories.js
src/components/forms/NumberField/NumberField.js
src/components/forms/NumberField/NumberField.stories.js
src/components/forms/RadioField/RadioField.js
src/components/forms/RadioField/RadioField.stories.js
src/components/forms/SelectField/SelectField.js
src/components/forms/SelectField/SelectField.stories.js
src/components/forms/TextField/TextField.js
src/components/forms/TextField/TextField.stories.js
src/story-utils/decorators.js
src/types/Form.js

These all need to be fixed to realize #435

Various cleanups, fixes and tweaks

---

package.json
src/components/formio/FormioComponent.js
src/components/formio/date.js
src/components/formio/email.js
src/components/formio/index.js
src/components/formio/radio.js
src/components/formio/textfield.js
src/components/formio/zod-schema.js
src/components/formio/zod-schema.spec.js
yarn.lock

Minimal formio integration with react tweaks required for #435
~~Depends on #490~~

Define formio empty value for component types

---

package.json
src/formio/components/Tooltips.stories.js
src/formio/templates/label.ejs
src/jstests/formio/components/editgrid.spec.js
src/scss/components/_tooltip.scss

Closes open-formulieren/open-forms#3209

Fix visibility tooltip text

---

src/components/appointments/ChooseProductStep.js
src/components/appointments/ChooseProductStep.stories.js
src/components/appointments/ContactDetailsStep.js
src/components/appointments/ContactDetailsStep.stories.js
src/components/appointments/Context.js
src/components/appointments/CreateAppointment/AppointmentProgress.js
src/components/appointments/CreateAppointment/CreateAppointment.js
src/components/appointments/CreateAppointment/CreateAppointment.stories.js
src/components/appointments/CreateAppointment/CreateAppointmentState.js
src/components/appointments/CreateAppointment/routes.js
src/components/appointments/DateSelect.js
src/components/appointments/DateSelect.spec.js
src/components/appointments/DateSelect.stories.js
src/components/appointments/LocationAndTimeStep.js
src/components/appointments/LocationAndTimeStep.spec.js
src/components/appointments/LocationAndTimeStep.stories.js
src/components/appointments/LocationSelect.js
src/components/appointments/LocationSelect.stories.js
src/components/appointments/ProductSelect.js
src/components/appointments/TimeSelect.js
src/components/appointments/TimeSelect.stories.js
src/components/appointments/story-utils.js
src/components/appointments/types.js

Partly closes #435
~~Depends on #491~~
Client-side validation for a better user-experience. Note that this does *not* absolve the backend from doing any validation :wink:

Add client-side validation for appointment form

---

src/formio/components/Map.stories.js

Document Formio map component in Storybook

---

.github/workflows/ci.yml
package.json

Let's uh... not add the badge for now :grimacing:

:construction_worker: Enable coverage reporting in CI

---

src/hooks/usePageViews.js

Fixes open-formulieren/open-forms#3268

[OF#3268] Add origin to url referrer

---

src/hooks/usePageViews.js

Fixes open-formulieren/open-forms#3268

[OF#3268] Backport 1.3.x - Add origin to url referrer

---

src/hooks/usePageViews.js

Fixes open-formulieren/open-forms#3268

[OF#3268] Backport 1.2.x - Add origin to url referrer

---

src/components/appointments/Context.js
src/components/appointments/CreateAppointment/AppointmentProgress.js
src/components/appointments/CreateAppointment/Confirmation.js
src/components/appointments/CreateAppointment/Confirmation.stories.js
src/components/appointments/CreateAppointment/CreateAppointment.js
src/components/appointments/CreateAppointment/CreateAppointment.stories.js
src/components/appointments/CreateAppointment/CreateAppointmentState.js
src/components/appointments/CreateAppointment/Summary.js
src/components/appointments/CreateAppointment/routes.js
src/components/appointments/LocationAndTimeStep.spec.js
src/components/appointments/mocks.js
src/components/appointments/story-utils.js
src/story-utils/decorators.js

Closes open-formulieren/open-forms#3067
Depends on #507

Appointment confirmation page

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml
src/i18n/compiled/nl.json
src/i18n/messages/nl.json

Partly closes open-formulieren/open-forms#3288

Prepare release 1.5.0-alpha.0

---

package.json
src/components/Map/Map.stories.js
src/components/Map/index.js
src/components/Map/mocks.js
src/components/Map/provider.js
src/components/Map/provider.spec.js
src/formio/components/Map.js
src/formio/components/Map.stories.js
src/formio/components/story-util.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/scss/components/_leaflet-map.scss
yarn.lock

Fixes open-formulieren/open-forms#2174
- added searchbar and button
- retrieved bag data

:sparkles: added searchbar in map component

---

src/components/forms/DateField/DateInputGroup.spec.js
src/components/forms/DateField/utils.js

Fix datefield month january

---

package.json
src/formio/components/Number.stories.js
src/formio/input-container-design-tokens.mdx
src/formio/input-container.stories.js
src/formio/templates/text.ejs
src/scss/components/_input-container.scss
src/styles.scss

Fixes https://github.com/open-formulieren/open-forms/issues/3045
- changed text.ejs file to use OF suffix
- added group styling to support suffix (and prefix if wanted later)
- added storybook story for number field with suffix

:sparkles: [#3045] implemented suffix for number field

---

src/components/appointments/ChooseProductStep.js
src/components/appointments/ChooseProductStep.spec.js
src/components/appointments/CreateAppointment/Summary.js
src/components/appointments/LocationAndTimeStep.js
src/components/appointments/Product.js
src/components/appointments/Product.stories.js
src/components/appointments/ProductSelect.js
src/components/appointments/ProductSelect.stories.js
src/components/appointments/mocks.js

Partially closes open-formulieren/open-forms#3332
Backend PR: https://github.com/open-formulieren/open-forms/pull/3338
When selecting one or more products and adding another product, the available options must be limited to valid options in combination with the earlier selected products.

Only allow selecting valid product combinations

---

src/api.js
src/components/Map/Map.stories.js
src/components/Map/MapAddress.scss
src/components/Map/NearestAddress.js
src/components/Map/index.js
src/components/Map/mocks.js
src/formio/components/Map.stories.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

fixes https://github.com/open-formulieren/open-forms/issues/2174
- Added function in the map component to fill in the searchbar with closest address based on the user map input

:sparkles: [#2174] added search bar address complete on map click

---

src/formio/validators/MinMaxTimeValidator.js
src/jstests/formio/components/time.spec.js

Fixes open-formulieren/open-forms#1884
Requires: https://github.com/open-formulieren/open-forms/pull/3345

[OF#1884] Support custom error for time component

---

src/components/appointments/Product.js
src/components/appointments/Product.stories.js
src/components/forms/NumberField/NumberField.js
src/components/forms/NumberField/NumberField.stories.js

Closes open-formulieren/open-forms#3299

Make amount field readonly when multiple products is not supported.

---

src/api.js
src/components/appointments/CancelAppointment.integration.spec.js
src/components/appointments/CreateAppointment/CreateAppointment.spec.js
src/components/appointments/CreateAppointment/CreateAppointmentState.js

Closes #505
Writing this test was *hard*

Reset session storage / cache on session expiry reset

---

src/api-mocks/submissions.js
src/components/appointments/Context.js
src/components/appointments/CreateAppointment/Confirmation.js
src/components/appointments/CreateAppointment/CreateAppointment.spec.js
src/components/appointments/CreateAppointment/CreateAppointmentState.js
src/components/appointments/CreateAppointment/Summary.js
src/components/appointments/CreateAppointment/Summary.spec.js

Closes #506  - depends on #534

Display backend processing error

---

src/components/appointments/ContactDetailsStep.js
src/components/appointments/CreateAppointment/CreateAppointment.spec.js
src/components/appointments/LocationAndTimeStep.js

Classic OWASP thing, fiddling with the URL and trying to bypass checks :)
Closes #508, depends on #535

Handle invalid states when accessing URLs directly

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.npm.md
README.rst
package.json
publiccode.yaml
src/i18n/messages/en.json
src/i18n/messages/nl.json

Prepare release 1.5.0

---

src/components/Map/Map.stories.js
src/components/StatementCheckboxes/StatementCheckbox.js
src/components/Summary/GenericSummary.js
src/components/Summary/Summary.stories.js
src/components/SummaryConfirmation/mocks.js
src/components/SummaryConfirmation/test.spec.js
src/components/appointments/CreateAppointment/Summary.js
src/i18n-zod.stories.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json

Release blocker in open-formulieren/open-forms#3415

Fix component key to intl message mapping

---

src/formio/components/Selectboxes.stories.js
src/formio/templates/field.ejs

Closes open-formulieren/open-forms#3418

💄[#3418] Stop showing * on not required selectboxes/radio

---

src/formio/components/Cosign.stories.js

[#309] Add co-sign component to storybook

---

src/components/appointments/ChooseProductStep.js
src/components/appointments/DateSelect.js
src/components/appointments/TimeSelect.js
src/components/appointments/utils.js

Closes open-formulieren/open-forms#3404

Respect multi-product time slot durations/amounts

---

src/components/App.js
src/components/appointments/ChooseProductStep.js
src/components/appointments/CreateAppointment/CreateAppointment.mdx
src/components/appointments/CreateAppointment/CreateAppointment.spec.js
src/components/appointments/CreateAppointment/routes.js

Closes open-formulieren/open-forms#3300

Pre-select product via query string

---

src/formio/validators/MinMaxTimeValidator.js
src/jstests/formio/components/time.spec.js

Fixes https://github.com/open-formulieren/open-forms/issues/1884

[OF#1884] Fine grained custom errors for time components

---

src/formio/components/DateField.stories.js
src/jstests/formio/components/date.spec.js

Part of open-formulieren/open-forms#3443

[OF#3443] PR Feedback

---

src/components/LoginOptions/LoginOptionsDisplay.js
src/scss/components/_login-options.scss

Fixes open-formulieren/open-forms#3414
I have chosen to add a padding to the whole div and align it with the buttons above. If you think it would be better to align all the buttons and not the div please let me know.

[OF#3414] Change co-sign section concerning styling

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml

* no new translation literals
* no dependency on new API version

Release 1.6.0 alpha

---

src/components/Map/MapAddress.scss
src/scss/components/_leaflet-map.scss

Fixes open-formulieren/open-forms#3510

[OF#3510] Fix overlapping address under map component

---

src/components/Summary/CosignSummary.js

Fixes https://github.com/open-formulieren/open-forms/issues/3523

[OF#3523] Fix cosign when no privacy concent enabled

---

src/components/ButtonsToolbar/index.js
src/components/ButtonsToolbar/test.spec.js
src/components/FormStep/index.js
src/components/Summary/GenericSummary.js
src/components/Summary/SubmissionSummary.js
src/components/Summary/Summary.stories.js
src/components/SummaryConfirmation/index.js
src/components/SummaryConfirmation/test.spec.js
src/components/appointments/CreateAppointment/CreateAppointment.stories.js
src/components/appointments/SubmitRow.js
src/scss/components/_toolbar.scss

[#464] Replace previous page button with anchor

---

package.json
src/components/Button/design-tokens.mdx
src/scss/components/_button.scss
src/scss/components/_language-selection.scss
src/scss/components/_login-button.scss
src/scss/components/_toolbar.scss
yarn.lock

Fix mobile button styling

---

.bumpversion.cfg
.editorconfig
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml
src/components/forms/Checkbox/Checkbox.js
src/formio/components/Select.stories.js
src/formio/templates/checkbox.ejs
src/formio/templates/columns.ejs
src/formio/templates/editGrid.ejs
src/formio/templates/radio.ejs
src/scss/components/_checkbox.scss
src/scss/components/_deprecated-select.scss
src/scss/components/_errors.scss
src/scss/components/_toolbar.scss
src/styles.scss

I've pushed a test build before to see if the webkit fix breaks other things, so marking this one as draft for now.
Closes #587

Release 2.0.0

---

src/formio/components/EditGrid.stories.js
src/formio/templates/editGridRow.ejs

Fixes https://github.com/open-formulieren/open-forms/issues/3576

[OF#3576] Fix empty label fields

---

package.json
src/formio/templates/editGridRow.ejs
src/scss/nl-design-system-community.scss

Fixes #469 
Needs: https://github.com/open-formulieren/design-tokens/pull/41

[#469] Add specific style for editgrid summary

---

package.json

[#36] Bump design tokens to 0.49.0

---

src/components/routingActions.js
src/sdk.spec.js

Fixes https://github.com/open-formulieren/open-forms/issues/3626

[OF#3626] Fix resume flow

---

src/sdk.js
src/sdk.spec.js

Fixes https://github.com/open-formulieren/open-forms-sdk/issues/605

:alembic: Attempt hot-fix for hash based routing

---

src/formio/components/PhoneNumberField.js
src/formio/components/PhoneNumberField.spec.js
src/formio/components/PhoneNumberField.stories.js

FIx phone number validation regex bug

---

src/components/forms/Label.js
src/formio/templates/checkbox.ejs
src/formio/templates/label.ejs
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Fixes open-formulieren/open-forms#3651

[OF#3651] Change "optional" field label to "not required"

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml

Part of open-formulieren/open-forms#3685

Release 2.1.0 alpha.0

---

src/components/auth/AuthenticationOutage.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Fixes open-formulieren/open-forms#3690

[OF#3690] Update outage texts according to B1

---

src/components/FormStepSummary/FormStepSummary.stories.js

Tests for #471 - should be merged first so that the refactor/rework branch can have visual regression tests against `main`.

:white_check_mark: Add stories for FormStepSummary component

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/components/Summary/Summary.stories.js
src/formio/components/AddressNL.js
src/formio/components/AddressNL.mocks.js
src/formio/components/AddressNL.stories.js
src/formio/components/story-util.js
src/formio/module.js
src/formio/templates/addressNL.ejs
src/formio/templates/library.js
src/formio/validators/plugins.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/jstests/formio/validators/pluginapivalidator.spec.js
src/sdk.js

Related to open-formulieren/open-forms#3607
---
Frontend summary (and backend as well, currently the same) might need to be tweaked:

Add address component

---

src/i18n/compiled/nl.json
src/i18n/messages/nl.json

:speech_balloon: [#619] Make Dutch text in map at B1 level

---

src/components/FormStepSummary/index.js
src/components/Summary/Summary.stories.js

Fixes https://github.com/open-formulieren/open-forms/issues/3778

[OF#3778] Render content component in summary

---

src/formio/validators/plugins.js
src/jstests/formio/validators/pluginapivalidator.spec.js

Fixes open-formulieren/open-forms#3797

[OF#3797] Fix plugin validator concerning repeating groups

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
docker/ci/config.json
package.json
publiccode.yaml
src/i18n/compiled/en.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Part of open-formulieren/open-forms#3767

Release 2.1.0

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package.json
publiccode.yaml

Seems to be quite a small one :tada:

Prepare release 2.2.0-alpha.0

---

src/components/AbortButton/AbortButton.js
src/components/AbortButton/AbortButton.mdx
src/components/AbortButton/AbortButton.stories.js
src/components/AbortButton/index.js
src/components/AbortionButton/index.js
src/components/ExistingSubmissionOptions.mdx
src/components/ExistingSubmissionOptions.stories.js
src/components/FormStep/index.js
src/components/Summary/GenericSummary.js

In preparation for https://github.com/open-formulieren/open-forms/issues/3791

[OF#3791] Add stories for existing submission options and rename Abort button

---

src/components/AbortButton/AbortButton.js
src/components/AbortButton/AbortButton.mdx
src/components/AbortButton/AbortButton.stories.js
src/components/ButtonsToolbar/index.js
src/components/ButtonsToolbar/test.spec.js
src/components/ExistingSubmissionOptions.js
src/components/ExistingSubmissionOptions.stories.js
src/components/Form.js
src/components/FormStart/index.js
src/components/FormStart/tests.spec.js
src/components/FormStep/FormStep.stories.js
src/components/FormStep/index.js
src/components/Summary/CosignSummary.js
src/components/Summary/GenericSummary.js
src/components/Summary/SubmissionSummary.js
src/components/Summary/Summary.stories.js
src/components/Summary/test.spec.js
src/components/appointments/SubmitRow.js
src/components/modals/FormStepSaveModal.js

Fixes https://github.com/open-formulieren/open-forms/issues/3791

[OF#3791] Abort button for anonymous user

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/components/Summary/Summary.stories.js

Fixes https://github.com/open-formulieren/open-forms/issues/3845
Not sure this is the right solution

Correctly render `content` component in summary

---

.github/workflows/ci.yml
.github/workflows/dockerhub-description.yml
.github/workflows/sb.yml

Most of these address the Node 16 -> Node 20 deprecation from Github.

:construction_worker: Bump github actions to their latest versions

---

package-lock.json
package.json

Fixes https://github.com/open-formulieren/security-issues/issues/26

Replace Formiojs with our own fork

---

src/components/FormStepSummary/ComponentValueDisplay.js

Partly fixes open-formulieren/open-forms#4009

[open-formulieren/open-forms#4009] Fix summary display of `fieldset`

---

src/formio/validators/utils.js
src/formio/validators/utils.spec.js

Partly closes open-formulieren/open-forms#4172
Also related to open-formulieren/open-forms#4158

Fix date validation

---

src/components/PostCompletionViews/StartPaymentView.js
src/components/PostCompletionViews/StartPaymentView.stories.js

Fixes open-formulieren/open-forms#4130

[open-formulieren/open-forms#4130] Do not show main url when asking for payment

---

src/Context.js
src/components/AbortButton/AbortButton.js
src/components/AbortButton/AbortButton.stories.js
src/components/PostCompletionViews/ConfirmationView.js
src/components/PostCompletionViews/ConfirmationView.stories.js
src/components/PostCompletionViews/PostCompletionView.js
src/components/analytics/GovMetricSnippet.js
src/components/analytics/utils.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/scss/components/_govmetric_snippet.scss
src/styles.scss

Fixes open-formulieren/open-forms#4115
:sparkles: Needs forward-port :sparkles: 
To do:
- Discuss the modal problem => Discussed: as long as the GovMetric questionnaire opened takes focus, then it's okay.
I could not get the questionnaire to open in an iframe :disappointed:

[#4115] Govmetric changes

---

src/formio/components/FileField.js
src/jstests/formio/components/file.spec.js

Partly fixes open-formulieren/open-forms#4222
I can't make the test to pass, it seems to not update the data when only calling `.upload` :/

 [open-formulieren/open-forms#4222] Fix max files upload limit 

---

src/formio/templates/field.ejs

Closes: https://github.com/open-formulieren/open-forms/issues/4220

:speech_balloon: [open-formulieren/open-forms#4220] Optional -> not required for grouped components

---

src/formio/components/Select.stories.js
src/scss/components/_deprecated-select.scss

Fixes open-formulieren/open-forms#4207

[open-formulieren/open-forms#4207] Fix styling overflow for select dropdown

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml

No translations updates for this one

Prepare release `2.3.0-alpha.0`

---

package.json
src/components/Form.js
src/components/Form.spec.js
src/components/LoginOptions/index.js
src/components/appointments/cancel/CancelAppointment.integration.spec.js
src/data/submissions.js

Issue: https://github.com/open-formulieren/open-forms/issues/4199
Related PR in backend: https://github.com/open-formulieren/open-forms/pull/4271

:sparkles: [open-formulieren/open-forms#4199] Explicitly start anonymous submission

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/components/Summary/Summary.stories.js
src/formio/components/AddressNL.js
src/formio/components/AddressNL.mocks.js
src/formio/components/AddressNL.stories.js
src/formio/components/EditGrid.stories.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Partly fixes open-formulieren/open-forms#3993

[OF#3993] Derive address functionality in addressNL component

---

.storybook/preview.js
src/components/modals/FormStepSaveModal.js
src/components/modals/FormStepSaveModal.stories.js
src/components/modals/Modal.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Fixes open-formulieren/open-forms#4382

[OF#4382] Missing client validation for email in the save and resume modal

---

src/components/FormStepSummary/ComponentValueDisplay.js
src/components/Summary/Summary.stories.js

Closes https://github.com/open-formulieren/open-forms/issues/4497

[OF#4497] Show correct address values when no city is found in addressNL summary

---

src/formio/components/AddressNL.stories.js
src/formio/components/EditGrid.stories.js
src/i18n/compiled/nl.json
src/i18n/messages/nl.json

partially fixes open-formulieren/open-forms#4505

:globe_with_meridians: [open-formulieren/open-forms#4505] Missing AddressNL translations

---

src/components/Form.js
src/components/Form.spec.js
src/data/submissions.js

Partly closes open-formulieren/open-forms#4397

[OF#4397] Extract `initial_data_reference` and send it to the backend

---

src/i18n/messages/nl.json

Closes open-formulieren/open-forms#4515

Update Dutch translations from formal to informal variant

---

src/components/FormStep/FormStep.stories.js
src/components/FormStep/index.js
src/components/FormStep/mocks.js
src/components/modals/Modal.js

Closes open-formulieren/open-forms#4643

Fix step submission being blocked by backend validation error

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Closes open-formulieren/open-forms#4777 (partially)

Prepare 2.5.0-alpha.0 release

---

src/components/FormStep/index.js
src/components/Sessions/SessionExpired.js
src/components/Summary/SubmissionSummary.js
src/components/appointments/CreateAppointment/CreateAppointment.spec.js
src/formio/components/FileField.stories.js
src/formio/templates/file.ejs
src/hooks/useTitle.js
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/scss/components/_deprecated-select.scss
src/scss/components/_progress-indicator.scss

Partially Closes open-formulieren/open-forms#4720
**Changes**
- Added focus styling to mobile progress menu toggle button and custom select input
- Descriptive links

Improve accessibility of navigation elements

---

package-lock.json
package.json
src/components/ProgressIndicator/index.js
src/hooks/useWindowResize.js
src/scss/components/_app.scss
src/scss/components/_checkbox.scss
src/scss/components/_content.scss
src/scss/components/_help-text.scss
src/scss/components/_label.scss
src/scss/components/_radio-field.scss

Partially closes open-formulieren/open-forms#4718
Changes regarding 1.4.10 Reflow

Textual and viewport accessibility improvements

---

src/api-mocks/analytics.js
src/api-mocks/submissions.js
src/components/Form.jsx
src/components/FormStep/index.jsx
src/components/FormStep/mocks.jsx

Part of open-formulieren/open-forms#3283, requires https://github.com/open-formulieren/open-forms/pull/4914

The backend now uses consistent casing in the API endpoints

---

src/story-utils/decorators.jsx

It doesn't seem to be used anywhere anymore.

:fire: Delete deprecated router decorator

---

src/i18n/compiled/nl.json
src/i18n/messages/nl.json

Only one string to translate :)

Update Dutch translations for the 3.0 release

---

src/components/AbortButton/AbortButton.jsx
src/components/AbortButton/AbortButton.stories.jsx
src/components/ButtonsToolbar/test.spec.jsx
src/components/ExistingSubmissionOptions.stories.jsx
src/components/FormStart/tests.spec.jsx
src/components/FormStep/FormStep.stories.jsx
src/components/Summary/Summary.stories.jsx
src/components/Summary/test.spec.jsx
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

closes open-formulieren/open-forms#4984

:speech_balloon: [open-formulieren/open-forms#4984] Change `abort` button to `cancel`

---

eslint.config.mjs
src/components/CoSign/index.jsx
src/components/Errors/ErrorBoundary.jsx
src/components/Form.jsx
src/components/FormDisplay.jsx
src/components/FormStep/index.jsx
src/components/LanguageSwitcher.jsx
src/components/LoginOptions/index.jsx
src/components/Map/provider.jsx
src/components/PostCompletionViews/StatusUrlPoller.jsx
src/components/PreviousLink.jsx
src/components/ProgressIndicator/ProgressIndicatorItem.jsx
src/components/ProgressIndicator/ProgressIndicatorItem.stories.jsx
src/components/ProgressIndicator/index.jsx
src/components/appointments/CreateAppointment/CreateAppointment.jsx
src/components/appointments/CreateAppointment/Summary.jsx
src/components/forms/FloatingWidget.jsx
src/components/modals/FormStepSaveModal.jsx
src/formio/components/AddressNL.jsx
src/formio/components/CoSignOld.jsx
src/formio/components/Map.jsx
src/hooks/useZodErrorMap.jsx

Turns out the .jsx files were not included by default :grimacing:

Fix linting config and associated code

---

src/components/Form.jsx
src/components/FormStep/FormStep.stories.jsx
src/components/FormStep/data.js
src/components/FormStep/index.jsx
src/components/PostCompletionViews/StartPaymentView.jsx
src/components/RequireSubmission.jsx
src/components/Sessions/SessionTrackerModal.jsx
src/components/formRoutes.jsx

Partly closes open-formulieren/open-forms#4929
* Refactored the `FormStep` component so that it can be extracted into the statically defined routes
* Had to refactor some supporting components around it to achieve that :-)

React router upgrade part 2

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml

Part of open-formulieren/open-forms#5126

Patch release 3.0.1

---

.bumpversion.cfg
CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json

Part of open-formulieren/open-forms#5176

Prepare release 3.1.0

---

src/components/FormStepSummary/ComponentValueDisplay.jsx
src/components/FormStepSummary/FormStepSummary.stories.jsx
src/formio/components/Partners/AddPartnerForm.stories.ts
src/formio/components/Partners/AddPartnerForm.tsx
src/formio/components/Partners/AddPartnerModal.stories.ts
src/formio/components/Partners/AddPartnerModal.tsx
src/formio/components/Partners/PartnerSubmitButton.tsx
src/formio/components/Partners/Partners.jsx
src/formio/components/Partners/Partners.stories.js
src/formio/components/Partners/PartnersForm.tsx
src/formio/components/Partners/definition.ts
src/formio/components/Partners/types.ts
src/formio/module.js
src/formio/templates/library.js
src/formio/templates/partners.ejs
src/i18n/compiled/en.json
src/i18n/compiled/nl.json
src/i18n/messages/en.json
src/i18n/messages/nl.json
src/scss/components/_data-list.scss

[#824] Add the partners component

---

src/components/FormStepSummary/ComponentValueDisplay.jsx

Closes open-formulieren/open-forms#5268 partly

[OF#5268] Fix duplicated data in the Partners' summary page

---

src/formio/components/Content.stories.jsx

This is updated (headings were added) because in the formio-renderer we need to have a reference for building the new component.
Seems that we lack some correct styles so they will be updated when the new design tokens version is added here.

Add some extra elements to the Content component (Headings)

---

package.json
src/developer-external-sb.mdx

Fix exports for downstream consumers

---

src/api.ts
src/components/FormDisplay.stories.tsx
src/components/FormDisplay.tsx
src/components/FormLandingPage.tsx
src/components/FormProgressIndicator.tsx
src/components/FormStart/FormStart.stories.ts
src/components/FormStart/index.tsx
src/components/FormStart/tests.spec.tsx
src/components/IntroductionPage/index.tsx
src/components/LoginOptions/index.tsx
src/components/ProgressIndicator/utils.ts
src/components/SubmissionProvider.tsx
src/data/submissions.ts
src/hooks/useInitialDataReference.ts
src/hooks/useStartSubmission.ts
src/routes/form.tsx
src/sdk.tsx

More Typescript conversion

---

.bumpversion.toml
CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml

Adds changes for the `3.3.0-alpha.1` release.

[#5522] Release 3.3.0-alpha.1

---

.bumpversion.toml
CHANGELOG.rst
README.NL.rst
README.rst
package-lock.json
package.json
publiccode.yaml
src/components/Map/Map.stories.jsx
src/i18n/compiled/nl.json
src/i18n/messages/nl.json

Adds the changes required for the `3.3.0` release.

Release 3.3.0

---

src/formio/components/Selectboxes.js
src/formio/components/Selectboxes.spec.js

backport of https://github.com/open-formulieren/open-forms-sdk/pull/868

Backport 3.1.x/checkbox in hidden fieldset
