open-formulieren/open-forms-sdk

src/formio/components/TextField.js
SDK PR for https://github.com/open-formulieren/open-forms/pull/499
Tested using both the Postcode component and a Textfield component for the postcode and the Textfield Component and Number component for the house number and both worked.  I tested with various formats of postcode (1015 CJ, 1015CJ, 1015cj, 1015 cj) and these all worked.  If an address is not found then the fields are just left blank.
Note: This does **not** work if the house number has a house letter appended (eg. 117a) since the BAG api returns a 400 if this is entered as a house number.  When 117 is filled in a request would be made to the backend and the fields would be autofilled but one would not be made after the 'a' was entered so if the user types 117a it's autofilled but not if they copy-and-pasted, for example. …
=> Autofill street name and city

src/components/Form.js, src/components/FormStep.js, src/components/LogoutButton.js, src/components/Summary.js, src/components/Summary/index.js, src/components/Summary/test.spec.js, src/i18n.js, src/scss/components/_button.scss, src/scss/components/_toolbar.scss
Related to https://github.com/open-formulieren/open-forms/issues/532
Currently this works as follows: if a form has a `loginRequired: true`, a logout button appears. It came to mind though that it is possible to have `loginRequired: false` but still specify an auth backend. In that case, it is still possible to login with DigiD/eHerkenning, but there will be no logout button.
Note: I didn't manage to add a test for `FormStep` to make sure the logout button is displayed :cry: The current problem is how to find a way around mocking `useImmerReducer`. 
Note 2: The difference in size build caused by replacing `import useAsync from 'react-use/esm/useAsync';` with `import {useAsync} from 'react-use';` is from 472.06 KB to 472.15 KB
=> Feature - Logout button

src/formio/components/FileField.js, src/formio/module.js
Fixes https://github.com/open-formulieren/open-forms/issues/524
The cause of the bug is that this functionality is not supported in FormIO v4.12.7 though it is supported in version 4.13.x so I copied the code from v4.13.0 into our code base.
Ref:
v4.13.0: https://github.com/formio/formio.js/blob/v4.13.0/src/components/file/File.js#L281-L304
v4.12.7: https://github.com/formio/formio.js/blob/v4.12.7/src/components/file/File.js#L271-L283
We could also bump the version up to v4.13.4 though this would require more testing to make sure the whole project still functions.
PDF
Image
=> Handle all mime types

src/sdk.js
This makes it possible for downstream packages to wire up their own components.
=> Export Formio exports

src/components/Form.js, src/components/FormStep.js, src/components/ProgressIndicator.js
Depends on the backend PRs that provide the API endpoint & form logic implementation.
The idea is that on every change that may affect the state/definition of the form, a check is done towards the backend with the latest form step data (debounced to allow for active typing by the user). The backend can then reply with modified form definition within the context of the existing submission data AND the currently filled out fields, even if these are not persisted yet to the backend.
=> Apply form logic while the user is filling out the form.

src/components/FormStep.js, src/components/FormStepSummary.js, src/formio/components/Select.js, src/utils.js
Changes needed for points
- Should have human readable values in summary page. Will need a way to save these human readable values after they have been selected.
- On the overview page, the appointment details are rendered weirdly
of https://github.com/open-formulieren/open-forms/issues/597
Related Backend Pull Request: https://github.com/open-formulieren/open-forms/pull/645
By saving both the id and name we can then access the name in the summary page and display it rather than the id.
This also formats the dates and times, both in the summary page and when choosing a date or time.
=> Improve appointments information in summary page

src/scss/components/_fieldset.scss
Fixes open-formulieren/open-forms#646
This should get us pretty close to the stylings shown in the ticket while still using the microscope-sass library.
After
Before
=> Update styling of fieldldset legend

src/api.js, src/components/Form.js, src/components/FormStart/index.js, src/formio/components/Select.js, src/hooks/useRecycleSubmission.js, src/utils.js
Fixes open-formulieren/open-forms#447
Right now after a page refresh the user will be redirected to the Form start page. The user needs to click on 'Start form' again to continue filling in the form. This means that if a user was logged in with DigiD, they will have to log in again (although if there is `?_start=1` in the URL the form will start anyway). 
Note: I couldn't manage to write a test for this :cry:
=> Save submission ID in localStorage

src/components/Form.js, src/components/FormStep.js, src/components/Summary/index.js, src/components/utils.js
Fixes open-formulieren/open-forms#225
TODO:
Backend PR: https://github.com/open-formulieren/open-forms/pull/706
=> Skip steps that are not applicable

src/formio/components/Email.js
Temporary fix for issue #79. 
This error happens because `setSelectionRange()` (used inside `restoreCaretPosition()`) can only be used on input fields of type text, search, URL, tel and password. 
Chrome throws errors if it is used on inputs of different types. https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange
This is fixed in FormIO 4.13, but upgrading currently causes other issues.
The problem with both this solution and the one from FormIO in 4.13, is that after entering your email in the form and waiting for the logic check to happen, the cursor goes back to the beginning of the email. This might make it frustrating to fill in a form.
=> [#79] Do nothing in restoreCaretPosition for email components

src/components/Form.js, src/components/PaymentOverview/__snapshots__/test.spec.js.snap, src/components/PaymentOverview/index.js, src/components/PaymentOverview/test.spec.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json
Fixes open-formulieren/open-forms#724
I've decided to keep it simple and possibly we can expand and include the payment button again if payment is not succesful. Given that we wipe all the session/state after completion, it'd be quite a bit of work to fetch that information again, and maybe we can leverage the `status` api endpoint to also display pricing information, but that's all extra complexity.
Screenshots:
Payment cancelled
Payment succeeded
Banktransfer leads to "processing" status
=> Display payment status

src/components/Form.js
Fixes open-formulieren/open-forms#709
The backend needs to know where the form originated for possible
future redirects (outside of the usual fill-out-form flow, such as
payment redirect, resuming the form or cancelling an appointment).
We include the formUrl parameter in the create data for this.
=> Include current browser location as form URL

src/api.js, src/hooks/useRecycleSubmission.js
Mentioned on Slack that we don't want to display this alert.  While nothing will currently use the alert I thought we should keep the code there in case we want it in the future, though we can also just remove it if that's preferred.
=> Don't call alert by default

src/components/Form.js
Partially fixes open-formulieren/open-forms#974
Fixes point `Investigate unexpected HTTP 403's while filling out the form - happens even when going from step to next step` 
The reason for at least one of the API call failures is that when we call dispatch then the component would re-render and so `useRecycleSubmission` was being called before we actually removed the submission id.  This would mean `useRecycleSubmission` would make an api call with a submission id that it should not since the submission was completed.
=> Remove submission ID before calling dispatch

src/components/Form.js, src/components/ProgressIndicator/index.js
To see if the steps 'overview' and 'confirmations' should be shown in the progress indicator, the component was looking at the submission. But on the start page, there is no submission.
=> ProgressIndicator breaks if no submission

src/components/FormStep.js, src/utils.js
Fixes open-formulieren/open-forms#1037
---
While logic checking and processing the logic check, race conditions
caused form inputs to behave erratically, often restoring input that
was previously changed. For example, typing a string in an input field,
having the logic complete and right at that moment hitting backspace
would undo the backspace actions at times.
This is caused by a race condition of new user input, updating the form
data state, while the logic check results processing would operate on
a slighter older version of that form data state.
This is NOT related to the debouncing of the check nor the API call
duration itself - on fresh input either the logic check is unscheduled,
ensuring the API call is not made in the first place, or if the API call
was initiated but hadn't …
=> Fixed race condition in logic-induced data updates

src/components/Form.js, src/components/FormStart/index.js, src/components/FormStep.js, src/components/FormStepSummary/utils.js
open-formulieren/open-forms#1174
There were more places were refs were updated with data that possibly
contained immutable datastructures (because they come from the
immer reducer state). These have now been wrapped with cloneDeep to
make them immutable as well, so that Formio can apply the mutations.
This typically happens when you have two fields for example: a regular
text field, and a multiple=true text field. If you edit the regular
text field, some immutable data ends up in the state, preventing you
from adding extra items to the multiple=true text field.
Additionally, the onFormIOChange event handler has been adapted, as
it did not update the internal view on the data after adding an
item to a multiple=true text field. This is caused by the
modifiedByHuman flag being 'undefined' …
=> More fixes w/r to Formio data immutability

src/formio/components/Select.js
open-formulieren/open-forms#1174
We can deconstruct the backend data back into something that the select
understands, based on the passed in options.
Additionally, when changing an appointment, the original time is no
longer available and the smallest atomic thing that can change for
the appointment, so we clear that value to not display ISO-8601 select
options that are auto-created by Formio because it's not present in
the available options list.
All of this is a nasty hack on top of a nasty hack. We really have to
revisit how the appointments stuff works.
=> Workaround for changing appointment data

src/components/FormStepSummary/ComponentValueDisplay.js, src/components/FormStepSummary/fixtures.js, src/components/FormStepSummary/test.spec.js
Fixes https://github.com/open-formulieren/open-forms/issues/1224
Fixes https://github.com/open-formulieren/open-forms/issues/1226
Note 1224:
The problem seems to be that some components with `multivalue` have as default value `[undefined]`. This broke the summary page.
Note 1226:
The main problem seemed to be that if components are inside hidden fieldsets, then they have a value `undefined` that broke the summary page.
=> [OF#1224] files

src/components/Form.js, src/components/ProgressIndicator/index.js, src/components/SubmissionConfirmation.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json
Fixes open-formulieren/open-forms#940
Depends on https://github.com/open-formulieren/open-forms/pull/1005
---
A plain link was quite ugly, so decided on a button in the bottom right (sticking to the user flow of starting top-left going to bottom-right).
The button is only displayed if:
* form is configured to display it
* there is no payment required - if payment is required you want people to enter that flow
**checkbox on full completion**
=> Display 'return to main website' on confirmation page

src/api.js, src/csrf.js, src/sdk.js
Fixes open-formulieren/open-forms#1410
This change makes it so:
1. Embedding pages can set the CSRF token needed for Open Forms (undocumented API)
2. If a CSRF token value is set, it is included as a request header
The DRF machinery in the backend requires the `SessionAuthentication` backend to be added to be able to recognize admin users (= users logged in to the Django admin of the backend). This in turns activates CSRF protection. The SDK is already configured to send cookies (required for the end user sessions), so the CSRF cookie - if set - is sent to the backend.
The AJAX calls need to send this token as a header (since POST bodies are JSON and not regular form-encoded data). Finally, we expose the control so the Open Forms backend (which embeds the SDK) can actually set the correct …
=> Make SDK CSRF header capable

src/formio/components/PhoneNumberField.js, src/formio/validators/plugins.js
Attempt at running the SDK part of https://github.com/open-formulieren/open-forms/issues/1452
There seems to be an issue where the invalidation error message doesn't show up in the form even though the API response with an invalidation response.
Backend PR: https://github.com/open-formulieren/open-forms/pull/1457#partial-pull-merging
=> [#1452] Enabled remote validators for PhoneNumberField

src/components/LoginButton/LoginButtonIcon.js, src/scss/components/_button.scss
Fixes open-formulieren/open-forms#1523
The cursor is now the default instead of pointer, and if you do click
the icon, the referenced href is opened in a new tab instead.
=> Do not give the illusion that the login button icon is a button

src/Context.js, src/hooks/useAutomaticRedirect.js, src/sdk.js
Fixes open-formulieren/open-forms#1533
The problem was that the hook `useAutomaticRedirect` was not checking the current location. So on any pathname without the `_start=1` queryparam it was redirecting to login.
=> [OF#1533] Infinite redirects

src/components/FormStepSummary/ComponentValueDisplay.js, src/components/FormStepSummary/fixtures.js, src/components/FormStepSummary/index.js, src/components/FormStepSummary/test.spec.js, src/components/FormStepSummary/utils.js, src/components/Summary/index.js, src/components/Summary/utils.js, src/components/Summary/utils.spec.js, src/utils.js
Related to open-formulieren/open-forms#1451
Mimicks the backend implementation with the renderer:
* Do not display column labels, ever
* Only display container elements if visible and has visible children
* Respect the component `showInSummary` config from form builder
=> Sort out summary rendering

src/components/FormStep.js, src/errors.js
Before submitting to the backend, run an explicit validation call. Returned errors are displayed with the component as validation error messages.
~~:warning: Depends on the new endpoint being merged in the backend.~~
=> Display step submission validation errors

package.json, src/api.js, src/components/ErrorBoundary.js, src/components/Form.js, src/components/FormStart/index.js, src/components/FormStep.js, src/errors.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json
This PR adds some robustness for backend errors with special attention for permission errors (HTTP 403).
* ensure that components that talk to the backend are wrapped in the error boundary
* throw HTTP 400-599 errors as exceptions
* track backend errors in component callbacks/event handlers/async calls
* display relevant information to the end-user
Example HTTP 403 error during login:
=> Handle HTTP 403 errors (and others)

src/formio/components/TextField.js, src/jstests/formio/components/textfield.spec.js
(Hopefully) fixes open-formulieren/open-forms#1832
* Only query location data when field is read-only or field has no value yet
* Debounce the location data querying
The backend has a patch which adds caching to further reduce the amount of requests sent to the BAG API.
Needs backporting to stable/1.0.x as well, and the debounce functionality should probably be ported to the main branch.
=> Fix location autofill flicker

src/formio/components/TextField.js, src/jstests/formio/components/textfield.spec.js
Taken from #220 
Debouncing helps preventing a tsunami of API calls firing for every
keystroke in the form. Additionally, it helps preventing bad auto-fill
because the relevant postcode/house number fields were only partially
filled (e.g. using 15 rather than 153 as house number).
=> Apply debounce behaviour from bugfix

src/api.js, src/components/FormStart/index.js, src/components/MaintenanceMode.js, src/components/ProgressIndicator/index.js, src/components/ProgressIndicator/test.spec.js, src/components/RequireSubmission.js, src/headers.js, src/sdk.js
We had discussed that having the 'header' word in the variable names made them a bit awkward to read when using them.
=> Change names of header variables to not include 'header'

src/components/FormStep.js, src/components/utils.js
open-formulieren/open-forms#2084
This is really a bandaid, but we should try to figure out why the `onReactSubmit` is triggered in the case of 
submitting an editgrid row with validation errors.
=> Check if the submit is triggered by a submit button

src/scss/components/_checkbox.scss
Before, on Brave (Chromium):
After (Brave):
After (Firefox):
=> :lipstick: Center checked radio circle

src/formio/templates/editGrid.ejs, src/scss/components/_editgrid.scss
Fixes open-formulieren/open-forms#2101
With group label:
If no group label is specified in the editor:
=> Add label to repeating group

src/components/FormStep.js, src/components/modals/FormStepSaveModal.js
Fixes open-formulieren/open-forms#2114
The generic logout endpoint was removed in 2.0.0, the submission- specific one needs to be used.
=> :bug: Replace removed session destroy endpoint

.storybook/preview-head.html, .storybook/preview.js, CHANGELOG.rst, src/components/Button.stories.mdx, src/styles.scss
Relates to open-formulieren/open-forms#2225
To avoid overriding design tokens from *other* themes, include our own scoped design token values only if the openforms theme is set.
=> :art: emit own styles/design tokens in openforms-theme scope

src/sdk.js, src/types/Form.js
since the djangorestframework-camel-case parser does not seem to parse i18nEnabled properly (it results in i_18n_enabled)
=> :truck: [#2232] Rename i18nEnabled -> translationEnabled

src/components/Form.js, src/components/LanguageSelection/LanguageSelection.js, src/components/LanguageSelection/LanguageSelection.stories.mdx, src/i18n.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json
Relates to https://github.com/open-formulieren/open-forms/issues/2256
This MVP has issues:
**Terrible UX**
1. The confirmation message needs improvement. But more importantly, it is shown in the current locale, which the user may not speak well.
1. The confirmation is oblivious of submission state; confusing confirmation shouldn't be asked if no data loss is at stake.
**Backend**
1. submissions are abandoned and left for a backend task to clean up
=> Restart submission on language changed

src/i18n.js, src/i18n.stories.mdx
Companion to open-formulieren/open-forms#2366
Now the language-specific formio translations are loaded on language changes.
=> Use new formio translation endpoints

src/components/Form.js
Fixes open-formulieren/open-forms#2256
Instead of going back to the start and presenting the user with the login options again, immediately start a new submission as their session should still be valid.
=> Restart submission on language change

src/components/Form.js
Don't start a new submission if none were already started. The user may not have logged in yet, and if the form requires login, user won't have permission to go to first step yet.
Stopped my attempt at writing `Form.spec.js` when after 3 mocks and 2 contexts in, I still didn't come past the Loader. There are way to many moving parts to make Form testable in isolation. :disappointed: 
Fixes open-formulieren/open-forms#2384
=> 🐛 [open-formulieren/open-forms#2384] Fix initial language switch

.editorconfig, src/Context.js, src/components/App.js, src/components/AppDisplay.js, src/components/AppDisplay.stories.mdx, src/components/Form.js, src/components/FormDisplay.js, src/components/FormDisplay.stories.mdx, src/components/Layout.js, src/components/ProgressIndicator/ProgressIndicatorDisplay.js, src/components/ProgressIndicator/index.js, src/custom-display-components.js, src/index.js, src/sdk.js
Fixes open-formulieren/open-forms#1517
Quick demo with some alternative layout (ugly [code](https://github.com/open-formulieren/open-forms-sdk/pull/295/files#diff-e2e7a692ca6f6636dc97a0ca1fd80791aecfe66b5c6e2fcd4cfdcb9987c07138)!):
(also 
)
=> Add support for pluggable/configurable replacement components

package.json, src/formio/templates/signature.ejs, src/scss/components/_button.scss
Fixes open-formulieren/open-forms#2270
Fixes open-formulieren/open-forms#2410
with a new proposal for a thicker border on-focus in buttons than the other elements that have a set focus style (like the radiobuttons).
The changes in this branch are related to the changes in this PR in the Design-Tokens repo: https://github.com/open-formulieren/design-tokens/pull/10
=> :wheelchair: nr.2270 add focus-styles and tabindex

src/formio/templates/label.ejs, src/formio/templates/radio.ejs
Closes open-formulieren/open-forms#2465 
- the label and radio templates were missing a tag that's used in the context of sanitizing HTML
=> [#2465] fix SDK templates

src/formio/components/Content.stories.mdx, src/formio/components/TimeField.stories.mdx
Fixes #325 
Took some time to find the root case: the `argTypes.customClass.control.labels` with an empty string is not happily accepted by storybook.
=> Fixed some storybook bugs

src/formio/templates/editGridRow.ejs, src/formio/templates/file.ejs, src/formio/templates/multiValueRow.ejs
Fixes open-formulieren/open-forms#2516
I went with `trash-can` instead of `trash` because I thought it looked nicer
=> [OF#2516] Replace crosses with bins

src/formio/templates/editGridRow.ejs
Fixes open-formulieren/open-forms#2440
=> [OF#2440] Don't display hidden components in repeating groups

.github/workflows/sb.yml, package.json, src/components/Card.stories.mdx
Closes #335
This is an attempt at setting up Turbosnap, with the pull request trigger intact. For PRs, the github action looks at the branch head commit to compare changes, which might work in our case and the one-flow git branching model.
=> :construction_worker: [#335] -- configure turbosnap

src/formio/components/FileField.js
Fixes open-formulieren/open-forms#2539 (partly).
Added support for mime type validation on the frontend where the default validation performed by formio doesn't work (e.g. the type of msg files is not recognized by browsers).
=> [#2539] fix mime type validation

package.json, src/scss/components/_leaflet-map.scss, src/scss/components/_select.scss
Fixes open-formulieren/open-forms#2686
The style was working in the SDK, but not in embedded forms. This is because this style in the backend was overwriting the style of the select component: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/scss/components/builder/_builder.scss#L78
Related token PR: https://github.com/open-formulieren/design-tokens/pull/16
=> [OF#2686] Add styles for select

src/formio/components/FileField.js
Part of fix for open-formulieren/open-forms#2911
=> Send heic/heif files to the server and trust their verdict over FormIO.

src/formio/components/FileField.js
This was previously fixed by adding the `abortUpload` method. But this gets overwritten during successful upload of a file here: https://github.com/formio/formio.js/blob/v4.13.13/src/components/file/File.js#L748. So this time I tried changing the event listener to directly update the fileDropHidden attribute
Fixes open-formulieren/open-forms#2912
=> [OF#2912] Fix disappearing drag and drop area

src/formio/components/Email.js
Fixes open-formulieren/open-forms#2909
=> [OF#2909] Fix restoreCaretPosition for email field

src/formio/templates/multiValueTable.ejs
Fixes open-formulieren/open-forms#2813
* style buttons that add another field as primary buttons
=> [#2813] make styling of add-buttons consistent

src/hooks/usePageViews.js
Fixes open-formulieren/open-forms#2875
* the `usePrevious` hook ([doc](https://usehooks.com/usePrevious/)) doesn't work properly and returns the same path/url for the current and previous page. It is replaced with a custom hook that stores current/previous values manually instead of relying on the magic of `useEffect`
* in addition, we send the full URL to siteimprove instead of path
=> [#2875] fix siteimprove

src/hooks/usePageViews.js
Closes open-formulieren/open-forms#3082
react-router does not take this into account by default, but that results in the form slug being cut off otherwise.
=> Take the basename/basepath into account for analytics

src/formio/templates/file.ejs, src/scss/components/_file-upload.scss
Closes open-formulieren/open-forms#2808
- Removed ellipsis and let filename wrap around
- Moved trashcan icon and filesize to separate line
=> [#2808] fix overflowing filenames

.storybook/main.js, src/components/FAIcon.js, src/components/PaymentOverview/__snapshots__/test.spec.js.snap, src/components/appointments/ChooseProductStep.js, src/components/appointments/ChooseProductStep.stories.mdx
Closes open-formulieren/open-forms#3063
Depends on #419
**Changes**
* Added repeating-group like layout to add/remove products
* Within a group you can select a product from API endpoint & specify the amount
* Ability to add additional products
* Stories document all the interactions
=> Implement product selection step component

src/components/Form.js, src/components/SubmissionConfirmation.js
Part of solution to open-formulieren/open-forms#2809
Complement to open-formulieren/open-forms#3108
- Changed `components.SubmissionConfirmation.js` to use dynamic title for download link
=> [#2809] make report download link title configurable

package.json, src/components/forms/DateField/DateField.js, src/components/forms/DateField/DateField.stories.mdx, src/components/forms/DateField/DatePickerCalendar.js, src/components/forms/DateField/index.js, src/components/forms/FloatingWidget.js, src/components/forms/FloatingWidget.stories.mdx, src/components/forms/index.js, src/formio/components/FileField.stories.mdx, src/scss/components/_date-picker.scss, src/scss/components/_floating-widget.scss, src/styles.scss, yarn.lock
Closes open-formulieren/open-forms#3060
~~Depends on open-formulieren/design-tokens#21~~
~~Depends on open-formulieren/design-tokens#22~~
**Notes**
* Field allows manual keyboard input in ISO 8601 format
* Date is stored in formik state (as string)
* Focusing the field opens the datepicker
* Supports specifying disabled dates, minimum and maximum date (all optional)
* Design token values in our own theme added to match existing look and feel
* Added documentation on what this component can and can not do
* Scoped to the needs of the appointments rework, see #433 for broader usage
**TODO**
=> Date field with date picker

src/components/appointments/TimeSelect.js, src/components/appointments/TimeSelect.stories.mdx, src/components/appointments/mocks.js
(Partially) closes open-formulieren/open-forms#3065
Depends on #450 
Implements the time field for the appointment time, based on select products, location and date. Times are displayed in the browser/OS timezone.
I've reached out to Chromatic support to ask if we can set the timezone for the play functions, but in the worst case we can disable this particular story completely.
=> Implement appointment time field

bin/find_untranslated_js.py, package.json, scripts/i18n-formatter.js, src/components/appointments/DateSelect.js, src/components/forms/DateField/DateField-datepicker.mdx, src/components/forms/DateField/DateField-datepicker.stories.js, src/components/forms/DateField/DateField-inputgroup.mdx, src/components/forms/DateField/DateField-inputgroup.stories.js, src/components/forms/DateField/DateField.js, src/components/forms/DateField/DateField.mdx, src/components/forms/DateField/DateInputGroup.js, src/components/forms/DateField/DatePicker.js, src/components/forms/DateField/utils.js, src/components/forms/InputGroup/InputGroup.js, src/components/forms/InputGroup/InputGroup.mdx, src/components/forms/InputGroup/InputGroup.scss, src/components/forms/InputGroup/InputGroup.stories.js, src/components/forms/InputGroup/index.js, src/components/forms/Label.js, src/components/forms/index.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json, src/scss/components/_input.scss, src/scss/nl-design-system-community.scss, src/story-utils/decorators.js
Partially closes #433 
* Added input group component(s)
* Added date field variant with input group widget
* Restructured Storybook documentation for date field
=> Datefield split inputs

src/components/forms/DateField/DateField-datepicker.stories.js, src/components/forms/DateField/DateField-inputgroup.stories.js, src/components/forms/DateField/DateInputGroup.js, src/components/forms/DateField/DatePicker.js, src/components/forms/DateField/hooks.js, src/components/forms/DateField/messages.js, src/components/forms/DateField/utils.js
Partially closes #433
This makes the input field for the date picker locale aware and more forgiving.
=> Locale aware datepicker

src/components/App.js, src/components/App.stories.js, src/components/Form.js, src/components/appointments/ChooseProductStep.js, src/components/appointments/LocationSelect.js, src/components/appointments/TimeSelect.js, src/components/appointments/index.js, src/sdk.js, yarn.lock
This wires up the appointment create form into the main app. For that, I broke up the main router into a native javascript array instead of JSX, which is the recommended way now in React Router - see the individual commits.
**Note** the product list API endpoint gives HTTP 403 errors if you don't have any form session/submission - that will be tackled in a separate PR.
In the future, this would be a good candidate for bundle splitting.
=> Hook up appointment form to main router

.storybook/decorators.js, .storybook/preview.js, src/api-mocks/submissions.js, src/components/Form.js, src/components/appointments/CreateAppointment.js, src/components/appointments/CreateAppointment.stories.js, src/data/submissions.js, src/hooks/useGetOrCreateSubmission.js
This hook ensures that a submission is created in the backend (and when done so, stores it in the browser session storage).
This is required for the backend permission checks, which require having a valid submission in the session.
The loader UI is displayed when the submission is being created, which prevents any other components from retrieving data from
the backend until a submission is available.
=> Ensure submission exists

src/components/Map/Map.stories.js, src/components/Map/index.js, src/formio/components/Map.js, src/map/constants.js
Fixes open-formulieren/open-forms#2175
- retrieved default zoom and location from configuration
- set starting location as configured latitude and longitude 
- set starting zoomlevel to be either map default or the configured zoomlevel
=> :sparkles: [#2175] added configureable zoom and start location

src/Context.js, src/api-mocks/submissions.js, src/components/App.js, src/components/App.stories.js, src/components/CoSign/Cosign.js, src/components/Form.js, src/components/SubmissionConfirmation.js, src/components/SubmissionConfirmation.stories.js, src/components/appointments/CreateAppointment/CreateAppointment.js, src/components/appointments/CreateAppointment/CreateAppointment.stories.js, src/developer-docs.mdx, src/hooks/useFormContext.js, src/sdk.js, src/story-utils/decorators.js
This refactors the existing application to pass the `form` via context so we can make the router routes statically defined and avoid some prop-drilling, moving more towards the intended usage of react-router's data routers.
=> Refactor form 'prop' and (nested) routes

src/api-mocks/submissions.js, src/components/SubmissionConfirmation.js, src/components/SubmissionConfirmation.stories.js, src/components/appointments/CreateAppointment/CreateAppointment.js, src/hooks/useGetOrCreateSubmission.js, src/hooks/usePoll.js
Related to open-formulieren/open-forms#3067
When implementing the confirmation state, the loading flag from the useGetOrCreateSubmission hook caused UI flicker due to unintended component remounting. This fixes the problem at the root so that developers don't really have to worry about the React internals.
Additionally, a story is added for the loading state - this should work in Chromatic because they disable CSS animations.
=> Fix submission state

package.json, yarn.lock
fixes #517 
- updated react leaflet to version 4.2.1
react-leaflet v3 doesn't support react v18: https://react-leaflet.js.org/docs/v3/start-installation/#adding-react-leaflet
=> :arrow_up: [#517] updated react-leaflet version to be compatibel with react v18

src/index.js, src/sdk.js
Closes open-formulieren/open-forms#3312
This one is hard to test due to CRA dev server/hot module replacement borking hard when adding a CSP to index.html, but the easiest is:
* Ensure you have CSP enabled in your backend
* Create a production build of this branch using `yarn build`
* Load a form (that is *not* CSP ignored) in the backend
* Check that the select dropdown now works
=> Ensure react-select emotion uses available CSP Nonce

package.json, src/components/Map/index.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json, src/map/index.js, src/scss/components/_leaflet-map.scss, yarn.lock
Fixes https://github.com/open-formulieren/open-forms/issues/2176
- Added leaflet-gesture-handling
- Implemented leaflet-gesture-handling
- removed zoomlevel as a argument from the setView in the MapView component
=> :heavy_plus_sign: [#2176] added gesture handling for leaflet

src/components/appointments/ChooseProductStep.js, src/components/appointments/ChooseProductStep.stories.js, src/components/appointments/ContactDetailsStep.js, src/components/appointments/ContactDetailsStep.stories.js, src/components/appointments/CreateAppointment/CreateAppointment.stories.js, src/components/appointments/LocationAndTimeStep.js, src/components/appointments/LocationAndTimeStep.stories.js, src/components/appointments/LocationSelect.js, src/components/appointments/ProductSelect.js, src/components/appointments/TimeSelect.js
Closes #514
Due to situations (hard refresh) where valid data is filled out, but no changes are made, the form is not considered to be dirty, which blocked the submit button. Relying on the valid state is not an alternative option either, as this requires validation to run on mount, which in turn discards the initialErrors set via the backend.
Additionally, running validation on blur/on change has some drawbacks in the UI:
- browser autocomplete does not fire onBlur, which requires another click or [Tab] by the user to blur the active input for validadtion to trigger
- blur on the datepicker input triggers validation to early when the user is still selecting a date in the calendar (possibly navigating to the next/previous month)
- blur on the date input group may trigger validation too …
=> Always allow formik submission and validate on submit

src/Context.js, src/components/App.js, src/components/Form.js, src/components/appointments/CancelAppointment.integration.spec.js, src/components/forms/EmailField/EmailField.js, src/components/forms/TextField/TextField.js, src/data/submissions.js, src/hooks/useGetOrCreateSubmission.js, src/sdk.js, src/sdk.spec.js
Partially closes open-formulieren/open-forms#3322
Two issues at hand here:
* the `form.isAppointment` handling caused the cancel URL to always redirect to the flow to create a new appointment
* the backend was not able to correctly reconstruct the cancel URL due to a deeply nested `formUrl` being passed to submission creation. This is now normalized base on the SDK `basePath` option (which specifies where a particular form is publicly hosted).
The handling of fragment routing in the backend is something that will still require particular attention, I've no idea yet how to do this :cry:
=> Fix appointment change and cancel links

src/Context.js, src/api-mocks/forms.js, src/components/LoginOptions/tests.spec.js, src/components/StatementCheckboxes/StatementCheckbox.js, src/components/Summary/Summary.stories.js, src/components/SummaryConfirmation/index.js, src/components/SummaryConfirmation/mocks.js, src/components/appointments/CreateAppointment/CreateAppointment.stories.js, src/components/appointments/CreateAppointment/Summary.spec.js, src/components/appointments/CreateAppointment/Summary.stories.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json
Closes open-formulieren/open-forms#3372
Reworked statement checkboxes to not hit the global configuration endpoint, but instead read the configuration from the form data retrieved from the form detail endpoint.
This also sets up the accessible message texts which were a bit too generic.
=> Support statement checkboxes per form

src/components/appointments/DateSelect.js, src/components/appointments/LocationAndTimeStep.js, src/components/appointments/LocationAndTimeStep.stories.js, src/components/appointments/LocationSelect.js, src/components/forms/DateField/DateField.js, src/components/forms/DateField/DateInputGroup.js, src/components/forms/DateField/DatePicker.js, src/components/forms/SelectField/SelectField.js
Closes #492
I'm not 100% convinced of this pattern yet - the thing is that formik's `Field` component automatically provides the `onChange` handler (and I'd like to keep that), so to do additional work we basically need to make sure to call the original handler.
This handler comes all the way from `formikContext.handleChange` and "wrapping" that thing is not trivial. An alternative would be to rely on `useEffect`, but that complicates things a lot more since you need to track previous values & do the comparisons, plus you require an additional render to actual reset things, while now the entire form values state update is batched in a single `onChange` event handler.
I'd like to let this simmer a bit and use the experience for the upcoming formio-renderer. Perhaps relying on the `Field` …
=> Appointment details: clear dependent field values

package.json, yarn.lock
Partly closes #433
This contains the fix for selecting any date in the calendar, even outside the current month.
Keyboard navigation is not included yet, but that's not a release blocker.
=> Upgrade @utrecht/component-library-react

src/formio/components/DateField.js, src/formio/components/DateField.stories.js, src/formio/validators/minMaxDateValidator.js
Fixes open-formulieren/open-forms#3443
Depends on https://github.com/open-formulieren/open-forms/pull/3479
I give up on the tests :cry:
=> [OF#3443] Date validation

src/formio/templates/checkbox.ejs, src/formio/templates/field.ejs
fixes https://github.com/open-formulieren/open-forms/issues/3419
updates class names of tooltip html components
=> :bug: [#3419] tooltips match design-token colour

src/components/FormStep/index.js
fixes https://github.com/open-formulieren/open-forms/issues/3385
disabled browser form validation
=> :sparkles: [#3385] disabled browser validation on form

src/scss/components/_progress-indicator.scss
The bar was not taking up full width due to the negative margin-left and margin-right values, combined with the width: 100% of the parent. Setting the width to calc(100% + 2 * margin) results in a horizontal scrollbar, but unsetting the width fixes the styling on mobile while not destroying it on desktop.
=> :lipstick: Fix width of progress indicator

src/formio/validators/plugins.js, src/jstests/formio/components/fixtures/phonenumber.js, src/jstests/formio/validators/mocks.js, src/jstests/formio/validators/pluginapivalidator.spec.js
Fixes open-formulieren/open-forms#3383
=>  [OF#3383] Refactor phone number validation

src/components/FormStep/index.js
Closes open-formulieren/open-forms#3511
Some difference in the JS engine in WebKit (the browser engine behind Safari or any other browser on iOS/MacOS) vs. Gecko (Firefox) and Blink (Chromium, Edge) seems to cause a different (debounce) behaviour and or event firing/acting on events w/r to the Formio renderer.
On Webkit, the formio initialized event triggered with mismatching backend data, causing the form field inputs to be cleared and the submission to be updated, which in turn triggers the logic check again due to a change event being fired. This then leads again to a change in the formio configuration and the formio renderer re-initializing, ad infinitum. Somewhere the form data and form configuration state goes out of sync and it's incredibly hard to manage this, especially due to …
=> Fix flickering inputs on Webkit browsers

src/components/forms/SelectField/SelectField.js
Closes #437
Solution taken from react-select issue/discussion.
There is some ambiguity on what the behaviour should be on MacOS, but due to lack of appropriate device we're leaving that as it is, for now.
=> Implement cursor start/end on Home/End keypress

CHANGELOG.rst, src/formio/validators/MinMaxTimeValidator.js, src/jstests/formio/components/fixtures/time.js, src/jstests/formio/components/time.spec.js
Closes open-formulieren/open-forms#3531
Final part in making these component definitions consistent.
Refs: open-formulieren/types#14, open-formulieren/open-forms#3532
=> moved minTime/maxTime validation to validate namespace

src/formio/components/TextField.js, src/formio/components/TextField.mocks.js, src/formio/components/TextField.stories.js
Closes open-formulieren/open-forms#2656
Simple fix - now the local scope of data is used instead of the global bucket of data.
=> Fix support for address autofill in editgrid

src/components/ProgressIndicator/index.js, src/components/ProgressIndicator/test.spec.js
Fixes open-formulieren/open-forms#2952
Part of https://github.com/open-formulieren/open-forms/pull/3551
Tests were refactored to use testing-library where possible (i.e. when using aria roles was possible)
=> ✨ [open-formulieren/open-forms#2952] Support form steps to be N/A by default

src/formio/templates/label.ejs, src/formio/templates/text.ejs
Fixes #524
A new attribute has been added (`aria-labelledby`) in order to combine multiple elements (`label`, `span`) and have a proper accessible name. This attribute identifies the element (or elements) that labels the element it is applied to. This was tested with Orca screen reader in Ubuntu (`super+alt+s` to enable it).
**References**:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby
https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA16 (example 3)
https://help.gnome.org/users/orca/stable/index.html.en
**Some remarks:**
- `aria-labelledby` can be used to reference another element to define its accessible name, when an element's accessible name needs to use content from elsewhere in the DOM
- The `aria-labelledby` property value can include …
=> [#524] Improve input element accessibility

package.json, src/components/EditGrid/EditGrid.js, src/components/EditGrid/EditGrid.stories.js, src/components/EditGrid/EditGridButtonGroup.js, src/components/EditGrid/EditGridItem.js, src/components/EditGrid/EditGridItem.stories.js, src/components/EditGrid/design-tokens.mdx, src/components/EditGrid/index.js, src/components/appointments/steps/ChooseProductStep.js, src/formio/templates/editGrid.ejs, src/formio/templates/editGridRow.ejs, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json, src/scss/components/_button-group.scss, src/scss/components/_editgrid.scss, src/scss/components/_language-selection.scss, src/styles.scss
Partially closes #454
Depends on open-formulieren/design-tokens#36
The markup is now more accessible and the theming of the edit grid can be done through design tokens. I tried to go shopping in the utrecht component library but couldn't find any appropriate existing components.
Tasks:
=> Use NL DS components (where possible) for edit grid component

src/components/FormStep/index.js
Fixes https://github.com/open-formulieren/open-forms/issues/3572.
The race condition happens after `onFormIOChange` is called a first time:
- Firefox
- WebKit
`onFormIOChange` will schedule a call to `evaluateFormLogic` that will in turn dispatch `BLOCK_SUBMISSION` (thus setting `canSubmit=false`). Logic check is performed, and `LOGIC_CHECK_DONE` is about to be dispatched (which will set `canSubmit` to `true` if the logic check allows it).
For some reason, having a colored HTML element triggers `onFormIOChange` at this specific time. On Firefox, `LOGIC_CHECK_DONE` was fired in time so it had time to set `canSubmit` to `true` again (as you can see `logicChecking` is `false` when this `onFormIOChange` call happens). However, WebKit seems to be to slow and `onFormIOChange` is called _before_ …
=> 🐛 Fix potential race condition on WebKit

src/components/appointments/CreateAppointment/CreateAppointment.spec.js, src/components/appointments/fields/Product.js, src/components/appointments/fields/Product.stories.js, src/components/appointments/fields/ProductSelect.js, src/components/appointments/fields/ProductSelect.stories.js, src/components/appointments/steps/ChooseProductStep.js, src/components/appointments/steps/ChooseProductStep.spec.js
Closes open-formulieren/open-forms#3536
This one kinda sucks because we need to pass (unvalidated) form data/state down to other form fields. Normalizing this with zod works as long as the data is valid, but crashes if the data is not valid. Allowing these empty/invalid inputs (-3 for example) in the validation schema weakens our actual validation and causes other problems downstream.
I think when we revisit this, we should not pass down the entire data structure or should use the context to obtain the data and bypass proptypes checking? I don't really see an elegant solution, so at least this patch will improve the UX.
=> Fix appointments crash

package.json, src/components/Button/design-tokens.mdx, src/scss/components/_button.scss, yarn.lock
I wasn't entirely satisfied yet with the changed focus ring on the button, and as there is no border-width design token for focus states, I think a CSS override in our own theme is the only viable option, but please convince me that I'm wrong!
I've also updated the design token documentation in storybook.
=> A couple more button tweaks

src/index.scss, src/styles.scss
The layout/container refactor (in the backend) broke the map styles in an 'interesting' way. We were loading the admin CSS for the form builder in the public frontend too, and that refactor PR realised this should not be needed and removed it. This admin CSS included the Leaflet CSS to be able to render the map in the form builder. It also provided the necessary CSS for the SDK maps, because it turns out the SDK never properly bundled the Leaflet CSS.
Cleaning up in the backend exposed this issue in the SDK, so now the import is moved to the SDK styles bundle to make it work reliably. This also means that the map component probably never worked properly with embedded forms on third party domains rather than served directly by our own backend.
The layout refactor is after Open Forms 2.4.0, …
=> :bug: Fix Leaflet styles

src/components/routingActions.js, src/sdk.js, src/sdk.spec.js
Fixes https://github.com/open-formulieren/open-forms/issues/3362
Linked to https://github.com/open-formulieren/open-forms/pull/3574
=> 🐛 Handle server side redirects

src/formio/validators/minMaxDateValidator.js, src/jstests/formio/components/date.spec.js
Fixes https://github.com/open-formulieren/open-forms/issues/3612
=> [OF#3612] Min and max date validation

src/formio/validators/MinMaxTimeValidator.js, src/jstests/formio/components/time.spec.js
Fixes https://github.com/open-formulieren/open-forms/issues/3611
=> [open-formulieren/open-forms#3611] Make time bounds validation inclusive

package.json, src/components/Anchor/Anchor.js, src/components/Anchor/Anchor.mdx, src/components/Anchor/Anchor.stories.js, src/components/ProgressIndicator/ProgressIndicatorItem.js, src/scss/components/_anchor.scss, src/scss/components/_progress-indicator.scss
Part of #36 
- Uses the `.utrecht-link--current` variant in the progress indicator
- Removed the `indent` and `muted` (custom) link variants
- Includes the (cherry-picked) patch for the hyphenation
=> Cleanup anchor modifiers

src/formio/components/TimeField.js, src/formio/components/TimeField.spec.js
Fixes open-formulieren/open-forms#3647
The behaviour is still not right: the validation only triggers on the 'on blur' event (so the check logic call happens with invalid data). But the backend doesn't crash anymore (with this fix https://github.com/open-formulieren/open-forms/pull/3670) so the form doesn't crash.
=> [#3647] Prevent invalid time from crashing form

src/scss/components/_columns.scss
... and design tokens.
This drops the usage of microscope-sass/bootstrap mixins/styling and aligns it with the appearance/behaviour of the new formio builder preview.
=> :recycle: Refactor columns styling to use CSS grid

src/formio/components/DateField.stories.js, src/formio/validators/minMaxDateValidator.js, src/jstests/formio/components/date.spec.js
Fixes open-formulieren/open-forms#3671
=> [OF#3671] Fix max date validation when current included

.storybook/preview.js
=> Add mobile/desktop tests in chromatic

src/formio/components/AddressNL.js, src/formio/components/AddressNL.stories.js, src/formio/validators/plugins.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json
Part of open-formulieren/open-forms#3607
=> Localize (validation error) messages

src/components/FormStepSummary/index.js, src/components/Summary/GenericSummary.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json, src/scss/components/_summary.scss
This was mentioned by @Robbert during our latest NL DS chat.
Rather than using `aria-describedby` I opted for `aria-label` to get good translatable messages - depending on the language, we can't anticipate how the form-designer provided `editStepText` properly fits into a sentence strung together from various DOM elements in a particular order.
=> Improve summary accessibility

src/components/forms/Label.js, src/components/modals/FormStepSaveModal.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json
Fixes https://github.com/open-formulieren/open-forms/issues/3805
=> [open-formulieren/open-forms#3805] Fix label if field is not required

src/components/forms/Label.js, src/formio/templates/checkbox.ejs, src/formio/templates/field.ejs, src/formio/templates/label.ejs, src/scss/components/_label.scss
In _formio_component.scss the field-required asterisk is removed because it is handled with the "utrecht-form-label--openforms-required" class. But this class was scoped on the "openforms-theme", meaning it did not work with other themes.
As the showing/hiding of the asterisk is a core functionality I think this css should be scoped on all themes. Styling can be further tweaked in the specific design system.
=> Make required asterisk theme-independant

src/components/Form.js
Fixes open-formulieren/open-forms#2617
=> [OF#2617] Retrieve needsPayment value from submission

src/components/App.js, src/components/Form.js, src/components/FormStart/index.js
Fixes open-formulieren/open-forms#3855
=> [OF#3855] Catch API errors on start submission

src/components/App.js, src/components/Form.js, src/components/Sessions/SessionExpired.js, src/components/Sessions/SessionExpired.stories.js, src/components/Sessions/SessionTrackerModal.js, src/components/Sessions/index.js, src/components/Summary/CosignSummary.js, src/components/appointments/CreateAppointment/CreateAppointment.js, src/components/appointments/CreateAppointment/CreateAppointment.spec.js, src/components/appointments/CreateAppointment/CreateAppointmentState.js, src/components/appointments/steps/ChooseProductStep.js, src/hooks/useSessionTimeout.js
=> Move session expiry page to own route

src/formio/components/Checkbox.scss, src/formio/components/Radio.stories.js, src/formio/components/Selectboxes.stories.js, src/formio/templates/radio.ejs, src/scss/components/_radio-field.scss
Closes #483
Renamed the branch, see here the previous PR: https://github.com/open-formulieren/open-forms-sdk/pull/658
=> :sparkles: [#483] add description to selectboxes and radio option

src/formio/components/FileField.js
Fixes open-formulieren/open-forms#4027
=>  [OF#4027] Turn url storage in valid constructor

src/components/FormStart/index.js
Fixes open-formulieren/open-forms#4082
A race condition is happening and the `useAsync` hook is being called three times, and `onFormStart` would be called every time as `onFormStartCalledRef` wasn't set to `true` by the first called in time.
This only happens when using a login button, as the `useAync` hook is watching on the `_start` query parameter, and a change to this query parameter seems to trigger the hook three times for some reason.
(This doesn't happen with the "Begin form" button as in this case, the `onFormStart` function is called directly).
=> [open-formulieren/open-forms#4082] Fix duplicate creation of submissions

src/Context.js, src/components/AbortButton/AbortButton.js, src/components/AbortButton/AbortButton.stories.js, src/components/PostCompletionViews/ConfirmationView.js, src/components/PostCompletionViews/ConfirmationView.stories.js, src/components/PostCompletionViews/PostCompletionView.js, src/components/analytics/GovMetricSnippet.js, src/components/analytics/utils.js, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json, src/scss/components/_govmetric_snippet.scss, src/styles.scss
Fixes open-formulieren/open-forms#4115
=> [#4115] Forwardport GovMetric to main

src/components/analytics/GovMetricSnippet.js
Fixes open-formulieren/open-forms#4328
This time checked by building the sdk
=> [open-formulieren/open-forms#4328] Fix images of Govmetric smileys not rendering

src/formio/components/AddressNL.js, src/formio/components/AddressNL.scss, src/formio/components/AddressNL.stories.js
Partly fixes open-formulieren/open-forms#4423
=> [OF#4423] Update addressNL component to render single/double column

.bumpversion.cfg, CHANGELOG.rst, README.NL.rst, README.rst, docker/ci/config.json, package-lock.json, package.json, publiccode.yaml
Release date is planned for next Tuesday, so tagging this branch as beta for testing purposes.
* Updated translations
* Bumped version
* Updated changelog
=> Prepare release 2.3.0

.storybook/preview.js, src/components/Button/OFButton.js, src/components/EmailVerification/EmailVerificationForm.js, src/components/EmailVerification/EmailVerificationForm.stories.js, src/components/EmailVerification/EmailVerificationModal.js, src/components/EmailVerification/EmailVerificationModal.stories.js, src/components/EmailVerification/EnterCodeButton.js, src/components/EmailVerification/ModeField.js, src/components/EmailVerification/SendCodeButton.js, src/components/EmailVerification/index.js, src/components/EmailVerification/mocks.js, src/components/Errors/ErrorBoundary.js, src/components/FormStep/FormStep.stories.js, src/components/FormStep/index.js, src/components/Summary/Summary.stories.js, src/components/modals/Modal.js, src/formio/components/Email.js, src/formio/components/Email.stories.js, src/formio/components/story-util.js, src/formio/templates/field.ejs, src/formio/templates/text.ejs, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json, src/scss/components/_form-field.scss, src/story-utils/decorators.js
Partially closes open-formulieren/open-forms#4542
The formio component (email) is extended so that a verify button is render, which triggers a modal to perform the actual verification.
TODO:
=> Implement email verification flow on the UI side

.bumpversion.cfg, CHANGELOG.rst, README.NL.rst, README.rst, package-lock.json, package.json, publiccode.yaml
Nothing changed compared to the beta. The release notes are the combination of the alpha and beta release notes.
=> :bookmark: Bump to version to 2.4.0 and update the release notes

src/sdk.js, src/sdk.spec.js
This is to make sure that all language elements will be translated to the newly selected language
=> [open-formulieren/open-forms#4600] Language switch now triggers an page reload

package-lock.json, package.json, src/components/ButtonsToolbar/index.js, src/components/ButtonsToolbar/test.spec.js, src/components/FormStep/index.js, src/components/IntroductionPage/index.js, src/components/PreviousLink.js, src/components/appointments/SubmitRow.js, src/scss/components/_previous-link.scss, src/scss/components/_start-link.scss, src/styles.scss
Closes open-formulieren/open-forms#4544
This PR allows you to configure (using the design tokens) if the previous link should be at the top, the bottom or both. By default the previous link is shown at the bottom (same as the current functionality).
This PR also adds the option to show an icon in the previous link (this is also configurable using design tokens)
To keep everything uniform, the arrow icon on the introduction page "start" button is changed to a Font Awesome icon.
=> :sparkles: [open-formulieren/open-forms#4544] Configurable form 'previous' link

src/components/Form.js, src/components/FormStart/index.js, src/components/FormStart/tests.spec.js, src/components/IntroductionPage/IntroductionPage.stories.js, src/components/IntroductionPage/index.js, src/components/LoginOptions/index.js
required for https://github.com/open-formulieren/open-forms/pull/4696
previously this was not passed properly, resulting in the initialDataReference not being sent on submissionCreate
=> :recycle: [open-formulieren/open-forms#4398] Cache initialDataReference to pass it with submissionCreate

src/components/Errors/ErrorMessage.js, src/components/Loader.js, src/components/Loader.stories.js, src/components/modals/Modal.js, src/i18n.js, src/i18n/messages/en.json, src/i18n/messages/nl.json, src/scss/components/_react-modal.scss
Closes open-formulieren/open-forms#4717
Some accessibility improvements involving aria tags, `role`'s and textual alternatives:
- The `Loader` element now has a textual alternative, which will be translated.
- The modals now use html buttons as buttons (instead of icons with a button role).
- The delete button/link for an file now specifies which file will be removed.
- And finally alerts now have `role="alert"`.
=> Improve a11y with aria attributes

src/formio/components/FileField.stories.js, src/formio/templates/file.ejs
The upload link uses the 'old' content (i.e. "browse"). With aria-label the additional context (about what kind of file/files are expected) is added
=> Accessible file upload link

src/formio/components/FileField.js, src/formio/components/SoftRequiredErrors.js, src/formio/components/SoftRequiredErrors.stories.js, src/formio/components/TextField.js, src/formio/components/TextField.spec.js, src/formio/module.js, src/formio/templates/library.js, src/formio/templates/missingFields.ejs, src/formio/utils.js, src/scss/components/_soft-required-errors.scss, src/styles.scss
Closes open-formulieren/open-forms#4546
This went better than I had anticipated.
* Implement 'content' component variant for the soft required validation errors
* Styled it as a common/regular warning alert
* Added escape hatches for background color/font color/font-weight in case it needs to look different from a regular alert
* Ensured accessibility (linked list header, form fields refer back to content)
* Added stories and unit tests
* Checked the template interpolation/rendering for XSS, seems to be okay.
Final tasks to wrap this up:
* Update formio translations in the backend
* Review documentation if anything extra is needed
=> Implement soft required validation

src/components/FormStart/index.js, src/components/FormStart/tests.spec.js, src/components/LoginOptions/index.js, src/components/utils/index.js
needed for https://github.com/open-formulieren/open-forms/pull/4696
previously this was added as a query param to the login URL, but to pass it correctly to the backend it should be added to the nextUrl query params on the login URL
=> :bug: [open-formulieren/open-forms#4546] Properly pass initial_data_reference

src/formio/components/Select.js, src/jstests/formio/components/select.spec.js
Fixes open-formulieren/open-forms#4772 partially
This was fixed in the formio-builder, but in order to fix it for OF 2.8.x and 2.7.x, this SDK workaround is applied
=> [Backport 2.4.x] 🐛 [open-formulieren/open-forms#4772] Fix select component with integer values

src/formio/components/Select.js, src/jstests/formio/components/select.spec.js
Fixes open-formulieren/open-forms#4772 partially
This was fixed in the formio-builder, but in order to fix it for OF 2.8.x and 2.7.x, this SDK workaround is applied
=> [Backport 2.3.x] 🐛 [open-formulieren/open-forms#4772] Fix select component with integer values

src/Context.js, src/components/Button/OFButton.mdx, src/components/CoSign/CoSign.stories.jsx, src/components/CoSign/Cosign.jsx, src/components/CoSign/CosignStart.jsx, src/components/CoSign/CosignStart.stories.js, src/components/FormStart/index.jsx, src/components/LoginOptions/LoginOptions.stories.jsx, src/components/LoginOptions/LoginOptionsDisplay.jsx, src/components/LoginOptions/index.jsx, src/components/LoginOptions/tests.spec.jsx, src/components/PostCompletionViews/ConfirmationView.jsx, src/components/PostCompletionViews/ConfirmationViewCosign.stories.js, src/components/PostCompletionViews/PostCompletionView.jsx, src/components/PostCompletionViews/StatusUrlPoller.jsx, src/components/routingActions.jsx, src/components/utils/index.jsx, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json, src/story-utils/decorators.jsx, src/types/Form.js
Closes open-formulieren/open-forms#4320 (partially), required for backend PR open-formulieren/open-forms#4808
=> Cosign improvements

src/components/ButtonsToolbar/test.spec.jsx, src/components/Summary/test.spec.jsx, src/components/SummaryConfirmation/test.spec.jsx
Closes #429
Closes #400
I think we're okay at the moment with which tests are unit test-like and which tests are interaction tests.
=> :art: [#429] Rewrite all React tests to testing-library

src/formio/components/TextField.js, src/formio/components/TextField.mocks.js, src/jstests/formio/components/textfield.mocks.js
Part of open-formulieren/open-forms#3283
Open Forms will no longer support api/v2/location/get-street-name-and-city, so we should use the new endpoint.
=> Updating address autocomplete endpoint

src/components/FormStepSummary/ComponentValueDisplay.jsx, src/components/Map/Map.stories.jsx, src/components/Map/index.jsx, src/components/Summary/Summary.stories.jsx, src/formio/components/Map.jsx
Part of open-formulieren/open-forms#2173
Adds a new property to the LeaftletMap component, named `tileUrl`. This allows the use of custom map backgrounds.
=> Custom map backgrounds

src/formio/components/EditGrid.stories.jsx, src/formio/templates/editGridRow.ejs
Closes open-formulieren/open-forms#4809
Updated the Formio templates for edit grid rows to use the utility which skips over layout components.
=> Avoid displaying layout components in editgrid summary

src/components/App.stories.jsx, src/components/Errors/ErrorBoundary.jsx, src/components/FormMaximumSubmissions.jsx, src/components/FormStart/index.jsx, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json
Closes open-formulieren/open-forms#4321 partly
=> [OF#4321] Make form unvailable when submission limit is reached

src/components/Form.jsx, src/components/Form.spec.jsx
Closes open-formulieren/open-forms#4918
=> :bug: [open-formulieren/open-forms#4918] Pass initial_data_reference when redirecting to formstart

.gitignore, build/plugins.mts, build/utils.mts, package.json, src/formio/components/Number.js, src/formio/validators/plugins.js, src/sdk.jsx, vite.config.mts
Depends on #758 to be merged first.
Should be a big milestone in #724 _provided everything still works as expected_
* Set up Vite so it can produce the UMD bundle like CRA/webpack did/does
* Set up Vite to produce a similar ESM build (but with less bugs than CRA/babel setup)
**TODO**
In a different PR we can then setup ESLint and swap out CRA with Vite :eyes: 
Tested this locally with a form that had a file upload component, optional text fields and date picker, all seems to work as expected. I've also tested the appointment form flow and it also works as expected. Once Open Forms 3.0 is released, this should be good to merge!
=> Configure Vite to build the SDK

.bumpversion.cfg, CHANGELOG.rst, README.NL.rst, README.rst, package-lock.json, package.json, publiccode.yaml
Closes open-formulieren/open-forms#4920 partly
=> Prepare release 3.0.0

.github/workflows/ci.yml, .github/workflows/sb.yml, codecov.yml, package-lock.json
Closes #724 
Storybook and vitest cover different parts of the codebase, and coverage checks fail sometimes because one is still running/not uploaded yet while the other one is. Tracking the coverage of these separately allows us to better judge which job produces which coverage.
Storybook tests should focus on interaction and not much on coverage, whereas vitest tests should ensure sufficient coverage is achieved.
=> Configure coverage flags for storybook/vitest

package.json, vite.config.mts
Partly closes #76
Vite/Rollup doesn't support chunking when bundling with UMD (which results in `window.OpenForms` being available), but when generating an ESM bundle this does work.
This adds a build/compile step which produces an experimental (un-optimized) ESM bundle to the build artifact so that our backend can start opting in to `<script type="module">...</script>` to initialize the SDK instead of using the UMD bundle. If that works as expected, I want to manage the chunks to avoid loading unused stuff (appointments, map...) unless they are actually used.
=> Build and distribute ESM bundle (next to UMD/ESM package)

src/formio/components/AddressNL.scss
Closes open-formulieren/open-forms#5003
=> [OF#5003] Update styling in addressNL component

src/components/LanguageSelection/LanguageSelection.jsx, src/components/LanguageSelection/LanguageSelection.stories.jsx, src/i18n.jsx, vite.config.mts
Partly closes #76
Verified by creating a static build and using it in our backend, switching between languages works as expected :tada:
=> Lazy load translations

src/formio/components/AddressNL.jsx
Partly closes: open-formulieren/open-forms#4699
This is regarding one of the issues described in the [OF#4699](open-formulieren/open-forms#4699) ticket:
> Sometimes the component validation triggers right after loading. The best way i can trigger this, is by making the component required and opening the frontend in incognito
The problem that caused this issues, was the default value of the addressNL component. This didn't conform to the expected value, which triggered a validation even before the user touched the form.
By setting the default value to an empty address this initial validation doesn't trigger
=> AddressNL component validation triggers on page load

src/formio/components/AddressNL.jsx
Partly closes: open-formulieren/open-forms#4699
The AddressNL component should only be rendered when it's not hidden. Otherwise, the attach function will call `createRoot` with an argument that isn't a DOM element. (Which causes an error being thrown in the front-end..)
So the creating of the root and, therefor, the rendering of the React component cannot be done. If the reactRoot doesn't exist, then it also doesn't (and cannot) be unmounted. So this is also something that shouldn't happen when the component is hidden.
This works fine when the component is hidden/shown using form logic, as the `hidden` property will be updated.
=> Don't render AddressNL component when it hidden

src/formio/components/AddressNL.jsx
Make sure that `get emptyValue()` stays a regular function. Making the `get emptyValue()` static results into weird validation issues, broken e2e tests, and general unpleasant behavior.
=> AddressNL unreliable validation fix

src/api-mocks/submissions.js, src/components/CoSign/Cosign.spec.jsx, src/components/Form.jsx, src/components/FormProgressIndicator.jsx, src/components/Summary/GenericSummary.jsx, src/components/Summary/SubmissionSummary.jsx, src/components/Summary/SubmissionSummary.stories.jsx, src/components/Summary/ValidationErrors.jsx, src/components/appointments/CreateAppointment/CreateAppointment.stories.jsx, src/i18n/compiled/en.json, src/i18n/compiled/nl.json, src/i18n/messages/en.json, src/i18n/messages/nl.json, src/scss/components/_card.scss
Closes open-formulieren/open-forms#4510 - requires the backend PR to be merged as that changes the API endpoint used here.
I've opted to collect all the errors at the top and group them by step, rather than trying to weave this in the summary table. User research from Utrecht showed that this was the best way to show validation errors.
Ideally, there would be some aria-describedby options, but that requires a lot more work to link everything together.
=> Display backend validation errors when submitting the form

.bumpversion.cfg, CHANGELOG.rst, README.NL.rst, README.rst, package-lock.json, package.json, publiccode.yaml, src/components/Summary/SubmissionSummary.stories.jsx, src/i18n/compiled/nl.json, src/i18n/messages/nl.json
Partly closes open-formulieren/open-forms#5102
=> Updated CHANGELOG and necessary files for 3.1.0-alpha.0 release

src/components/FormStart/index.jsx
Closes open-formulieren/open-forms#5046
=> Remove login buttons when the submission limit is reached

src/components/Map/LeafletMap.jsx, src/components/Map/types.jsx
Part of open-formulieren/open-forms#5038
Because the geoJsonGeometry is available before the featureGroupRef is set, can the useEffect hook not draw the map shapes.
This fix makes sure that featureGroupRef is set, so that map shapes can be drawn
=> Missing map shapes in summary step

src/formio/components/SoftRequiredErrors.js, src/formio/components/SoftRequiredErrors.stories.js
Fixes open-formulieren/open-forms#5086
=> [OF#5086] Fix showing soft requirement warning in hidden components

src/scss/components/_button-group.scss
The @utrecht/button-group-react package pulls in the button-group-css dependency which keeps implementation + styles in sync. So, we can use the new CSS package in favour of the (outdated and no longer published) @utrecht/components package.
=> :art: Use button-group-css isolated package

src/components/Button/OFButton.jsx
Closes open-formulieren/open-forms#5192 partly
This has to do with the `disabled` submit button
=> [OF#5192] Fix buttons styling after refactor

src/components/CoSign/CosignStart.jsx, src/components/CoSign/CosignStart.stories.js
Closes open-formulieren/open-forms#5195
Cosign always requires users to authenticate and whether the form can be started anonymously or not has no influence on the cosign start options.
=> Ensure anonymous form start button is not displayed for cosign start

src/sdk.jsx
Closes: open-formulieren/open-forms#5242
Browser translations, in participle the translation functions of Chrome, change the DOM tree when translating texts. This causes React to lose track of certain DOM nodes, which leads to the SDK throwing errors and crashing.
This solution ensures that no SDK content can be translated. With this we lose some accessibility, but this seems to be the only reliable solution that would "solve" the issue for any and all browsers and translation plugins.
=> Dropping support for browser translations

src/components/Map/LeafletMap.jsx
Partly closes open-formulieren/open-forms#5191
This ensures that the map shows the entire geometry shape in the summary view. Additionally, this re-fits the map when the user draws a shape.
=> Fit map to geometry bounds

src/formio/components/DateField.js
Closes open-formulieren/open-forms#5240
Closes open-formulieren/open-forms#4820
Fixed the serialization of the calendar value to an actual proper date string instead of datetime, which now also works with suspending forms. Talk about an old bug...
@viktorvanwijk I think this one can also be included in the patch releases still :)
=> Fix date field value normalization to date from datetime

src/hooks/useRecycleSubmission.js
Fixes open-formulieren/open-forms#5266
The presence of an initial data reference parameter implies it's a new reference, which would invalidate any existing submissions stored in the local storage. So, the easiest (but not most elegant) patch for the observed problem is to ignore any existing submission ID from the local storage (or session storage, if you will) when this query param is present.
This works because the parameter is only used to bootstrap the process and kept around long enough to be able to send it with the submission create call. After that, it's no longer passed around in the URL, and navigating back to the form start step while on step 2 or further will present the 'continue or reset' screen as usual because the parameter is missing.
When the parameter is present, it's …
=> Don't offer to re-use submission for (new) initial data reference

src/components/auth/AuthenticationError.spec.tsx, src/components/auth/AuthenticationErrors/index.jsx, src/components/auth/constants.ts
Making sure that failed Yivi login attempts (due to general errors or the user canceling) are handled correctly by the SDK, by showing an appropriate error message.
=> open-formulieren/open-forms#5132 Handling failed Yivi login attempts
